// Bible-grounded quiz replacement builder & applier.
// Run: node scripts/build_bible_replacements.js
//
// REPLACES the 322 non-Bible entries in src/data/all_questions.json with
// new Bible-grounded questions (Catholic canon — includes deuterocanonical
// books). Target IDs:
//   - Level 3 classic:    q_l3_1   .. q_l3_100  (100 items)
//   - Level 4 classic:    q_l4_1   .. q_l4_94   (94 items)
//   - Level 5 classic:    q_l5_1   .. q_l5_100  (100 items)
//   - Teka-gambar Level 2:teka_21  .. teka_40  (20 items)
//   - Teka-gambar Level 3:teka_41  .. teka_48  (8 items)
// Total: 322 items.

const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const JSON_PATH = path.join(REPO, 'src', 'data', 'all_questions.json');

// ============================================================
// REPLACEMENT DATA
// ============================================================

// Helper — wrap content into a question row with explicit level/category/difficulty.
const c = (cat, lvl, diff) => (q) => ({ ...q, category: cat, level: lvl, difficulty: diff, gameMode: q.gameMode || 'classic' });
const OT3 = c('old_testament', 3, 'hard');
const NT3 = c('new_testament', 3, 'hard');
const OT4 = c('old_testament', 4, 'hard');
const NT4 = c('new_testament', 4, 'hard');
const OT5 = c('old_testament', 5, 'hard');
const NT5 = c('new_testament', 5, 'hard');

// ------- LEVEL 3 (100 Bible questions, medium-hard) -------
//   Prophets (15) + Wisdom (15) + Historical OT (20) + Gospels/Acts (25) + Epistles (25)
const LEVEL3 = [
  // Prophets (15)
  OT3({ id:'q_l3_1', question:"Yesaya bernubuat tentang seorang anak dara yang akan melahirkan anak bernama?", options:["Imanuel","Mesias","Yesaya","Yerusalem"], correctAnswer:0, explanation:"Yesaya 7:14 — 'Seorang perempuan muda akan mengandung dan melahirkan seorang anak laki-laki, dan ia akan menamakan dia Imanuel' (artinya 'Allah menyertai kita'). [Yesaya 7:14]" }),
  OT3({ id:'q_l3_2', question:"Hamba yang menderita dalam Yesaya 53 menggambarkan nubuat tentang?", options:["Raja Daud","Nabi Yesaya","Mesias yang akan datang","Seorang hamba biasa"], correctAnswer:2, explanation:"Yesaya 53 menggambarkan Hamba YHWH yang menderita untuk keselamatan ramai — ditafsirkan Kristiani sebagai nubuat tentang Mesias. [Yesaya 53:3-5]" }),
  OT3({ id:'q_l3_3', question:"Nabi Yeremia dipanggil Tuhan pada usia muda. Apa janji Tuhan kepadanya?", options:["Jangan takut, Aku besertamu","Menjadi raja","Berkahwin dengan cepat","Pergi ke Babel"], correctAnswer:0, explanation:"Yeremia 1:8 — 'Janganlah takut kepada mereka, sebab Aku besertamu untuk melepaskan engkau, demikianlah firman TUHAN'. [Yeremia 1:8-10]" }),
  OT3({ id:'q_l3_4', question:"Yunus dibuang ke mana apabila kapalnya dilanda ribut?", options:["Ke padang pasir","Ke dalam laut","Ke Bait Suci","Ke sebuah gua"], correctAnswer:1, explanation:"Yunus 1:15 — 'Lalu mereka mengangkat Yunus dan melemparkannya ke dalam laut'. Sebab itu Allah menyediakan ikan besar. [Yunus 1:15, 1:17]" }),
  OT3({ id:'q_l3_5', question:"Binatang pertama dalam penglihatan Daniel 7 (singa berkepala dua) melambangkan empayar mana?", options:["Babilon","Persia","Yunani","Roma"], correctAnswer:0, explanation:"Daniel 7:4 — 'Yang pertama seperti singa, tetapi ia mendapat sayap rajawali'. Singa = Babilon. [Daniel 7:1-4]" }),
  OT3({ id:'q_l3_6', question:"Kitab Obaja merupakan kitab terpendek dalam Perjanjian Lama. Ia menubuatkan tentang kejatuhan?", options:["Babilon","Edom","Filistin","Amalek"], correctAnswer:1, explanation:"Kitab Obaja bernubuat tentang kejatuhan Edom — keturunan Esau yang bermusuhan dengan Israel. Hanya 21 ayat. [Obaja 1-21]" }),
  OT3({ id:'q_l3_7', question:"Mikha menubuatkan tempat kelahiran Mesias iaitu di?", options:["Yerusalem","Nazaret","Betlehem Efrata","Kapernaum"], correctAnswer:2, explanation:"Mikha 5:1 — 'Dan engkau, hai Betlehem Efrata... dari padamu akan keluar bagi-Ku seorang yang menjadi pemerintah di Israel'. [Mikha 5:1]" }),
  OT3({ id:'q_l3_8', question:"Penglihatan tulang kering di lembah (Yehezkiel 37) melambangkan?", options:["Kekalahan Babel","Kebangkitan semula Israel","Kehancuran Bait Suci","Kedatangan Mesias"], correctAnswer:1, explanation:"Yehezkiel 37 — tulang-tulang kering yang menjadi hidup semula adalah gambaran pemulihan bangsa Israel selepas pembuangan. [Yehezkiel 37:1-14]" }),
  OT3({ id:'q_l3_9', question:"Maleakhi menubuatkan kedatangan nabi sebelum Tuhan. Nabi itu ialah?", options:["Musa","Elia","Yesaya","Daniel"], correctAnswer:1, explanation:"Maleakhi 4:5 — 'Lihat, Aku akan mengutus nabi Elia kepadamu'. Yesus menafsirkan ini sebagai Yohanes Pembaptis. [Maleakhi 4:5]" }),
  OT3({ id:'q_l3_10', question:"Hosea menikahi Gomer sebagai simbol bagi?", options:["Kesetiaan Allah","Ketidaksetiaan Israel","Kejayaan Israel","Penawanan Israel"], correctAnswer:1, explanation:"Hosea menikahi Gomer sebagai gambaran ketidaksetiaan Israel — dan kesetiaan Allah yang tetap memulihkan. [Hosea 1:2-3]" }),
  OT3({ id:'q_l3_11', question:"Yoel menubuatkan tentang pencurahan Roh pada 'hari terakhir' — dirujukkan kepada?", options:["Salib","Pentakosta","Kedatangan Kristus","Paskah"], correctAnswer:1, explanation:"Yoel 2:28 — 'Aku akan mencurahkan Roh-Ku ke atas semua manusia'. Petrus merujukkan ini pada Pentakosta (Kisah 2:16-17). [Yoel 2:28]" }),
  OT3({ id:'q_l3_12', question:"Kitab Amos menentang ketidakadilan sosial pada zaman raja?", options:["Salomo","Yerobeam II","Ahab","Hiskia"], correctAnswer:1, explanation:"Amos 1:1 — bernubuat pada zaman Yerobeam II raja Israel, menentang penindasan. [Amos 1:1]" }),
  OT3({ id:'q_l3_13', question:"Habakuk menubuatkan 'orang benar akan hidup oleh'?", options:["Harta","Kerja keras","Iman","Ibadat"], correctAnswer:2, explanation:"Habakuk 2:4 — 'Orang benar akan hidup oleh iman'. Paulus merujukkan ayat ini dalam Roma 1:17. [Habakuk 2:4]" }),
  OT3({ id:'q_l3_14', question:"Zakharia menubuatkan raja yang rendah hati dan menunggang?", options:["Kuda","Keledai","Unta","Lembu"], correctAnswer:1, explanation:"Zakharia 9:9 — 'Lihat, rajamu datang kepadamu, ia rendah hati dan menunggang seekor keledai'. Genap pada kemasukan Yesus. [Zakharia 9:9]" }),
  OT3({ id:'q_l3_15', question:"Yesaya menubuatkan suara di padang gurun yang mempersiapkan jalan Tuhan — digenapi oleh?", options:["Yesus","Yohanes Pembaptis","Elia","Yesaya sendiri"], correctAnswer:1, explanation:"Yesaya 40:3 — 'Suara yang berseru-seru di padang gurun: Sediakanlah jalan Tuhan'. Yohanes Pembaptis menggenapi. [Yesaya 40:3, Matius 3:3]" }),
  // Wisdom (15)
  OT3({ id:'q_l3_16', question:"Kitab Ayub mengisahkan tentang seorang yang kehilangan segala-galanya tetapi tetap?", options:["Murtad","Setia kepada Allah","Memberontak","Meninggalkan kota"], correctAnswer:1, explanation:"Ayub 1:21 — 'Tuhanlah yang memberi, Tuhanlah yang mengambil, terpujilah nama Tuhan'. [Ayub 1:21, 2:10]" }),
  OT3({ id:'q_l3_17', question:"Mazmur 23 mula dengan frasa?", options:["Tuhan gunung batuku","Tuhan gembalaku","Tuhan pelitaku","Tuhan terangku"], correctAnswer:1, explanation:"Mazmur 23:1 — 'Tuhan adalah gembalaku, takkan kekurangan aku'. [Mazmur 23:1]" }),
  OT3({ id:'q_l3_18', question:"Amsal 3:5-6 'Percayalah kepada Tuhan dengan segenap hatimu dan...'?", options:["Jangan menyandarkan pengertian kepada dirimu sendiri","Bergantung pada hartamu","Meminta kepada orang lain","Mendengarkan ibu bapa sahaja"], correctAnswer:0, explanation:"Amsal 3:5-6 — 'Percayalah kepada Tuhan dengan segenap hatimu, dan janganlah bersandar kepada pengertianmu sendiri'. [Amsal 3:5-6]" }),
  OT3({ id:'q_l3_19', question:"Pengkhotbah 3:1-8 menyenaraikan ada waktunya untuk segala sesuatu — berapa pasangan peristiwa?", options:["Tujuh","Sepuluh","Lapan","Tiga"], correctAnswer:2, explanation:"Pengkhotbah 3:1-8 menyenaraikan lapan pasang peristiwa: lahir/mati, tanam/mencabut, dll. [Pengkhotbah 3:1-8]" }),
  OT3({ id:'q_l3_20', question:"Kitab Kebijaksanaan memuji hikmat yang lebih berharga daripada?", options:["Keperangan","Perak dan emas","Kuasa politik","Makanan"], correctAnswer:1, explanation:"Kebijaksanaan 7:8-9 — 'Aku lebih menghargai kebijaksanaan daripada kesehatan dan kegemilangan'. [Kebijaksanaan 7:8-9]" }),
  OT3({ id:'q_l3_21', question:"Sirakh (Ecclesiasticus) pasal 3 membahas tentang?", options:["Pernikahan","Hormat kepada ibu bapa","Peperangan","Pertanian"], correctAnswer:1, explanation:"Sirakh 3:1-16 menekankan kewajiban menghormati ibu bapa — janji panjang umur dan berkat. [Sirakh 3:1-16]" }),
  OT3({ id:'q_l3_22', question:"Mazmur yang paling panjang dalam Alkitab ialah?", options:["Mazmur 119","Mazmur 117","Mazmur 23","Mazmur 150"], correctAnswer:0, explanation:"Mazmur 119 adalah mazmur terpanjang dengan 176 ayat — membahas Kitab Taurat. [Mazmur 119:1-176]" }),
  OT3({ id:'q_l3_23', question:"Kitab Kidung Agung ialah puisi cinta antara?", options:["Daud dan Batsyeba","Salomo dan seorang gadis Sulami","Saul dan Mikhal","Yusuf dan Asenat"], correctAnswer:1, explanation:"Kidung Agung 6:13 menyebut 'Gadis Sulami' — puisi cinta antara raja dan gadis. [Kidung Agung 6:13]" }),
  OT3({ id:'q_l3_24', question:"Mazmur 51 ditulis oleh Daud setelah peristiwa?", options:["Membunuh Goliat","Berzina dengan Batsyeba","Mengusir Absalom","Penobatan jadi raja"], correctAnswer:1, explanation:"Mazmur 51 — ditulis selepas ditegur Nabi Natan kerana dosa dengan Batsyeba. [Mazmur 51, 2 Samuel 11-12]" }),
  OT3({ id:'q_l3_25', question:"Pengkhotbah 12:13 merumuskan tugas manusia iaitu?", options:["Mencari hikmat","Takut akan Allah dan berpegang pada perintah-Nya","Mengumpulkan harta","Mendapatkan pengetahuan"], correctAnswer:1, explanation:"Pengkhotbah 12:13 — 'Takutlah akan Allah dan berpeganglah pada perintah-perintah-Nya, karena ini adalah kewajiban setiap orang'. [Pengkhotbah 12:13-14]" }),
  OT3({ id:'q_l3_26', question:"Amsal 31:10-31 menggambarkan wanita yang baik; akrostiknya menggunakan huruf Ibrani untuk perkataan?", options:["Suami","Isteri","Anak","Rumah"], correctAnswer:1, explanation:"Amsal 31:10 — 'Siapakah dapat menemukan wanita yang kuat?'. Setiap ayat bermula dengan huruf Ibrani untuk 'isteri'. [Amsal 31:10-31]" }),
  OT3({ id:'q_l3_27', question:"Kitab Kebijaksanaan 2 mengutuk orang fasik yang berkata?", options:["Marilah menyimpan keadilan","Marilah menikmati kesenangan dunia","Marilah berpuasa","Marilah berkorban"], correctAnswer:1, explanation:"Kebijaksanaan 2:1-9 — 'Marilah kita menikmati kesenangan dunia'. [Kebijaksanaan 2:1-9]" }),
  OT3({ id:'q_l3_28', question:"Mazmur 18 bermula dengan?", options:["Berbahagialah orang","Aku mengasihi Engkau, ya TUHAN","Tuhan gembalaku","Ya TUHAN, janganlah menghukum aku"], correctAnswer:1, explanation:"Mazmur 18:1 — 'Aku mengasihi Engkau, ya TUHAN, kekuatan-ku'. [Mazmur 18:1]" }),
  OT3({ id:'q_l3_29', question:"Kebijaksanaan 7:22-23 menghuraikan Roh Kebijaksanaan sebagai roh yang?", options:["Roh kuasa","Roh yang tenang, lembut dan mudah memerintah","Roh peperangan","Roh yang tenang dan keras"], correctAnswer:1, explanation:"Kebijaksanaan 7:22-23 — 'Ada dalam hikmat itu suatu roh yang arif, yang kudus... yang lembut, yang mudah memerintah'. [Kebijaksanaan 7:22-23]" }),
  OT3({ id:'q_l3_30', question:"Kata Ibrani 'hebel' (kesia-siaan) muncul kira-kira berapa kali dalam Pengkhotbah?", options:["5 kali","10 kali","Sekitar 30 kali","Sekali sahaja"], correctAnswer:2, explanation:"'Hebel' muncul kira-kira 30 kali — tema utama kitab Pengkhotbah. [Pengkhotbah 1:2, 1:14, 2:1, 2:11, 2:15]" }),
  // Historical OT (20)
  OT3({ id:'q_l3_31', question:"Pada zaman Hakim-Hakim, setiap orang melakukan apa yang benar menurut pandangannya sendiri kerana?", options:["Tiada raja","Tiada imam","Tiada nabi","Tiada kota"], correctAnswer:0, explanation:"Hakim-Hakim 21:25 — 'Pada zaman itu tidak ada raja di antara orang Israel'. [Hakim-Hakim 21:25]" }),
  OT3({ id:'q_l3_32', question:"Rut ialah menantu perempuan Moab yang mengikut Naomi ke?", options:["Yerusalem","Betlehem","Yerikho","Mesir"], correctAnswer:1, explanation:"Rut 1:22 — 'Mereka sampai ke Betlehem pada permulaan musim menuai jelai'. [Rut 1:22]" }),
  OT3({ id:'q_l3_33', question:"Daud dipilih menjadi raja kerana apa yang dilihat oleh Samuel?", options:["Kekuatan","Ketinggian","Hati","Wajah"], correctAnswer:2, explanation:"1 Samuel 16:7 — 'Manusia melihat apa yang di depan mata, tetapi Tuhan melihat hati'. [1 Samuel 16:7, 16:12]" }),
  OT3({ id:'q_l3_34', question:"Tabut Perjanjian dibawa orang Filistin ke mana?", options:["Yerusalem","Asdod","Bait Suci","Bukit Sion"], correctAnswer:1, explanation:"1 Samuel 5:1-2 — dibawanya ke Asdod, di rumah Dagon berhala mereka. [1 Samuel 5:1-5]" }),
  OT3({ id:'q_l3_35', question:"Salomo berhikmat meminta apa dalam mimpi di Gibeon?", options:["Harta","Hikmat untuk memimpin bangsa","Kemenangan peperangan","Isteri yang cantik"], correctAnswer:1, explanation:"1 Raja-raja 3:5-9 — Salomo meminta hikmat. [1 Raja-raja 3:5-12]" }),
  OT3({ id:'q_l3_36', question:"Elia berdoa berapa kali di Gunung Karmel sehingga api turun?", options:["3 kali","4 kali","7 kali","12 kali"], correctAnswer:2, explanation:"1 Raja-raja 18:36-38 — tujuh kali pengulangan. [1 Raja-raja 18:36-38]" }),
  OT3({ id:'q_l3_37', question:"Tobit menjadi buta kerana?", options:["Kecelakaan","Kotoran burung merpati masuk ke matanya","Sakit tua","Pukulan"], correctAnswer:1, explanation:"Tobit 2:10 — 'Tibalah di sebelah kananku kotoran burung merpati yang masih hangat ke dalam kedua mataku'. [Tobit 2:10]" }),
  OT3({ id:'q_l3_38', question:"Malaikat yang menemani Tobias dalam perjalanan ke Media ialah?", options:["Mikha'el","Rafael","Gabriel","Uriel"], correctAnswer:1, explanation:"Tobit 5:16 — 'Aku ialah Rafael, salah satu dari tujuh malaikat kudus'. [Tobit 5:16, 12:15]" }),
  OT3({ id:'q_l3_39', question:"Yudit membunuh Holofernes dengan cara?", options:["Dengan pedang dari luar","Dengan batu","Dengan memenggal kepalanya dengan pedangnya sendiri","Dengan tombak"], correctAnswer:2, explanation:"Yudit 13:6-8 — Yudit menghampiri Holofernes yang mabuk dan memenggal kepalanya. [Yudit 13:6-8]" }),
  OT3({ id:'q_l3_40', question:"Ratu Ester menyelamatkan bangsa Yahudi di kota?", options:["Babel","Susa","Yerusalem","Tigris"], correctAnswer:1, explanation:"Ester 1:1-2 — peristiwa berlaku di kota Susa, ibu kota empayar Persia. [Ester 1:1-2]" }),
  OT3({ id:'q_l3_41', question:"Kitab Ezra membahas tentang?", options:["Kehidupan di Mesir","Kembali dari pembuangan ke Yerusalem","Peperangan Daud","Kehidupan Daniel"], correctAnswer:1, explanation:"Kitab Ezra dan Nehemia menceritakan kembalinya bangsa Yahudi dari pembuangan. [Ezra 1:1-4]" }),
  OT3({ id:'q_l3_42', question:"Kitab 1 Makabe menceritakan Revolusi Makabe yang diperjuangkan oleh?", options:["Yudas Makabe","Simon Hasmonea","Yohanes Hirkanus","Aristobulus"], correctAnswer:0, explanation:"1 Makabe 3:1-9 — Yudas Makabe memimpin Revolusi Makabe. [1 Makabe 3:1-9]" }),
  OT3({ id:'q_l3_43', question:"Raja Hizkia memimpin pemurnian Bait Suci dengan?", options:["Para imam dan orang Lewi","Para nabi","Pasukan tentera","Rakyat asing"], correctAnswer:0, explanation:"2 Tawarikh 29:3-5 — Hizkia mengumpulkan imam-imam dan orang-orang Lewi. [2 Tawarikh 29:3-5]" }),
  OT3({ id:'q_l3_44', question:"Pembuangan di Babel berlangsung selama?", options:["30 tahun","50 tahun","70 tahun","100 tahun"], correctAnswer:2, explanation:"Yeremia 25:11-12 — 'Tujuh puluh tahun lamanya'. [Yeremia 25:11-12]" }),
  OT3({ id:'q_l3_45', question:"Nabi Elia diangkat ke syurga dengan cara?", options:["Kapal terbang","Kereta berapi dan kuda berapi","Malaikat","Angin ribut"], correctAnswer:1, explanation:"2 Raja-raja 2:11 — 'Datanglah kereta berapi dan kuda berapi, lalu memisahkan keduanya'. [2 Raja-raja 2:11]" }),
  OT3({ id:'q_l3_46', question:"Bait Suci Pertama dibina oleh Salomo di gunung?", options:["Nebo","Sinai","Moria","Tabor"], correctAnswer:2, explanation:"2 Tawarikh 3:1 — Salomo membangun rumah Tuhan di gunung Moriah. [2 Tawarikh 3:1]" }),
  OT3({ id:'q_l3_47', question:"Rut berkata 'Di mana engkau mati, aku akan mati di situ' yang bermaksud?", options:["Kesetiaan penuh","Mengikuti keluarga","Menjadi kaya","Mengikuti adat"], correctAnswer:0, explanation:"Rut 1:16-17 — pernyataan kesetiaan Rut kepada Naomi. [Rut 1:16-17]" }),
  OT3({ id:'q_l3_48', question:"Gideon meminta tanda kepada Allah melalui?", options:["Api","Bulu domba dan embun","Batu","Apiun"], correctAnswer:1, explanation:"Hakim-Hakim 6:36-40 — Gideon meminta dua tanda dengan bulu domba. [Hakim-Hakim 6:36-40]" }),
  OT3({ id:'q_l3_49', question:"Dalam peristiwa menara Babel, manusia berusaha membina menara yang sampai ke?", options:["Langit","Tanah","Tempat tinggi","Bandar"], correctAnswer:0, explanation:"Kejadian 11:4 — 'Marilah kita buat kota dan menara yang puncaknya sampai ke langit'. [Kejadian 11:1-9]" }),
  OT3({ id:'q_l3_50', question:"Ester menemui raja tanpa dipanggil. Menurut hukum Persia ini boleh membawa kepada?", options:["Kematian","Pengampunan","Penghargaan","Pengasingan"], correctAnswer:0, explanation:"Ester 4:11 — 'Siapa yang masuk kepada raja di ruangan dalam tanpa dipanggil, haruslah mati'. [Ester 4:11]" }),
  // Gospels + Acts (25)
  NT3({ id:'q_l3_51', question:"Yesus pertama kali menampakkan diri selepas kebangkitan kepada?", options:["Maria Magdalena","Petrus","Tomas","Paulus"], correctAnswer:1, explanation:"1 Korintus 15:5 — 'Dan Ia menampakkan diri kepada Kefas'. [1 Korintus 15:5]" }),
  NT3({ id:'q_l3_52', question:"Dalam perumpamaan tentang domba yang sesat (Lukas 15), berapa ekor domba yang ada?", options:["10","99","100","120"], correctAnswer:2, explanation:"Lukas 15:4 — 'Siapakah di antara kamu yang mempunyai seratus ekor domba'. [Lukas 15:4]" }),
  NT3({ id:'q_l3_53', question:"Yesus menyembuhkan sepuluh orang kusta, berapa yang kembali mengucap syukur?", options:["Semua","Tujuh","Satu","Dua"], correctAnswer:2, explanation:"Lukas 17:15-18 — hanya satu orang Samaria yang kembali 'memuliakan Allah'. [Lukas 17:15-18]" }),
  NT3({ id:'q_l3_54', question:"Saul/Paulus mengalami pertobatan di jalan ke?", options:["Yerusalem","Damsyik","Antiokhia","Roma"], correctAnswer:1, explanation:"Kisah 9:1-9 — Saul menuju Damsyik ditimpa cahaya dari langit. [Kisah 9:1-9]" }),
  NT3({ id:'q_l3_55', question:"Pada Pentakosta, Roh Kudus turun ke atas murid dalam bentuk?", options:["Burung merpati","Api","Angin","Awan"], correctAnswer:1, explanation:"Kisah 2:3 — 'Tampaklah kepada mereka lidah yang terpecah-pecah, seperti lidah api'. [Kisah 2:1-4]" }),
  NT3({ id:'q_l3_56', question:"Murid-murid Yesus yang pertama dipanggil adalah?", options:["Petrus dan Yohanes","Simon Petrus dan Andreas","Yakobus dan Yohanes","Filipus dan Bartolomeus"], correctAnswer:1, explanation:"Matius 4:18-20 — pertama kali memanggil Simon Petrus dan Andreas. [Matius 4:18-20]" }),
  NT3({ id:'q_l3_57', question:"Yesus memberikan kuasa kepada 12 rasul untuk?", options:["Menjadi raja","Menyembuhkan orang sakit dan mengusir setan","Mengumpulkan wang","Mendirikan gereja"], correctAnswer:1, explanation:"Markus 6:7 — memberikan kuasa untuk mengusir roh jahat. [Markus 6:7]" }),
  NT3({ id:'q_l3_58', question:"Yesus mati di kayu salib di gunung yang bernama?", options:["Zaitun","Golgota","Sinai","Nebo"], correctAnswer:1, explanation:"Yohanes 19:17 — 'Ia keluar ke tempat yang bernama Tengkorak, dalam bahasa Ibrani disebut Golgota'. [Yohanes 19:17]" }),
  NT3({ id:'q_l3_59', question:"Maria Magdalena datang ke kubur pada hari?", options:["Sabtu","Minggu pertama","Senin","Selasa"], correctAnswer:1, explanation:"Markus 16:2 — 'Pada hari pertama minggu itu, pagi-pagi benar, mereka datang ke kubur'. [Markus 16:2, Yohanes 20:1]" }),
  NT3({ id:'q_l3_60', question:"Yesus menubuatkan bahawa Petrus akan menyangkal-Nya sebanyak?", options:["Dua kali","Tiga kali","Lima kali","Tujuh kali"], correctAnswer:1, explanation:"Lukas 22:34 — 'engkau sudah menyangkal Aku tiga kali'. [Lukas 22:34]" }),
  NT3({ id:'q_l3_61', question:"Konsili pertama di Yerusalem memutuskan bahawa?", options:["Orang bukan Yahudi mesti disunat","Orang bukan Yahudi tidak perlu disunat tetapi menjauhkan diri dari daging berhala","Semua mesti berpuasa","Petrus menjadi paus"], correctAnswer:1, explanation:"Kisah 15:28-29 — Konsili Yerusalem memutuskan menjauhkan diri dari daging berhala, darah, dll. [Kisah 15:19-29]" }),
  NT3({ id:'q_l3_62', question:"Surat Galatia membahas masalah utama?", options:["Menyembah berhala","Menyembah malaikat","Keperluan bersunat untuk keselamatan","Hari Sabat"], correctAnswer:2, explanation:"Galatia 2:16 — Paulus menentang keperluan sunat. [Galatia 2:16]" }),
  NT3({ id:'q_l3_63', question:"Yohanes Pembaptis memakai pakaian daripada?", options:["Linen halus","Bulu unta dan ikat pinggang kulit","Kain wol","Bulu domba"], correctAnswer:1, explanation:"Matius 3:4 — 'Yohanes sendiri memakai pakaian bulu unta'. [Matius 3:4, Markus 1:6]" }),
  NT3({ id:'q_l3_64', question:"Doa Bapa Kami diajarkan Yesus di mana?", options:["Bukit Zaitun","Sermon di atas Bukit","Kapernaum","Khemah Pertemuan"], correctAnswer:1, explanation:"Matius 6:9-13 — Doa Bapa Kami dalam konteks Sermon di atas Bukit. [Matius 6:9-13]" }),
  NT3({ id:'q_l3_65', question:"Yesus menunjukkan tubuh-Nya kepada Tomas dengan berkata?", options:["Katakanlah imanmu","Taruhlah jarimu di sini dan lihatlah tangan-Ku","Pergilah ke Galilea","Sukacitakan"], correctAnswer:1, explanation:"Yohanes 20:27 — 'Taruhlah jarimu di sini dan lihatlah tangan-Ku'. [Yohanes 20:27]" }),
  NT3({ id:'q_l3_66', question:"Surat Yakobus kepada diaspora merujuk kepada?", options:["12 suku Israel","Orang Yahudi di pembuangan","Orang percaya Kristus yang disebar di seluruh dunia","Tujuh gereja di Asia"], correctAnswer:2, explanation:"Yakobus 1:1 — 'kepada kedua belas suku yang ada di perantauan'. [Yakobus 1:1]" }),
  NT3({ id:'q_l3_67', question:"Yesus berkata 'Akulah jalan, kebenaran dan hidup' di kitab?", options:["Matius","Markus","Lukas","Yohanes"], correctAnswer:3, explanation:"Yohanes 14:6 — 'Yesus berkata kepadanya: Akulah jalan, dan kebenaran, dan hidup'. [Yohanes 14:6]" }),
  NT3({ id:'q_l3_68', question:"Di Padandan, Paulus dan Silas menyanyi di penjara. Tiba-tiba berlaku?", options:["Api jatuh","Gempa bumi","Banjir","Malaikat"], correctAnswer:1, explanation:"Kisah 16:25-26 — 'Tiba-tiba terjadilah gempa bumi'. [Kisah 16:25-26]" }),
  NT3({ id:'q_l3_69', question:"Yesus membawa tiga murid ke gunung transfigurasi: Petrus, Yakobus dan?", options:["Tomas","Yohanes","Andreas","Matius"], correctAnswer:1, explanation:"Matius 17:1-2 — 'Yesus membawa Petrus, Yakobus dan Yohanes saudaranya'. [Matius 17:1-2]" }),
  NT3({ id:'q_l3_70', question:"Surat Pertama Korintus membahas topik seperti?", options:["Perpecahan jemaah, perkawinan, karunia rohani, kebangkitan","Yesus sebagai Mesias, kasih Allah","Pengharapan, iman, kasih","Nubuat kiamat"], correctAnswer:0, explanation:"1 Korintus 1:10-13 (perpecahan), 1 Kor 12 (karunia rohani), 1 Kor 15 (kebangkitan). [1 Korintus 1-16]" }),
  NT3({ id:'q_l3_71', question:"Surat Kolose mengajarkan Kristus sebagai?", options:["Seorang nabi","Kepala tubuh, yaitu jemaah","Raja negara","Hamba Allah"], correctAnswer:1, explanation:"Kolose 1:18 — 'Dan Ia adalah kepala tubuh, yaitu jemaah'. [Kolose 1:18, 1:15-20]" }),
  NT3({ id:'q_l3_72', question:"Yesus menyembuhkan orang lumpuh di Kolam Betesda. Tradisi menyebut berapa lama?", options:["5 tahun","10 tahun","38 tahun","Lama"], correctAnswer:2, explanation:"Yohanes 5:5 — 'Di sana terdapat seorang yang sudah 38 tahun sakit'. [Yohanes 5:5]" }),
  NT3({ id:'q_l3_73', question:"Yesus menyamakan diri-Nya dengan 'roti yang turun dari syurga' dalam kitab?", options:["Matius 5","Yohanes 6","Matius 26","1 Korintus 11"], correctAnswer:1, explanation:"Yohanes 6:35 — 'Aku adalah roti hidup'. [Yohanes 6:35, 6:48, 6:51]" }),
  NT3({ id:'q_l3_74', question:"Tujuh gereja yang menerima surat-kitab Wahyu terletak di Asia Kecil. Berapa kota?", options:["Lima","Enam","Tujuh","Lapan"], correctAnswer:2, explanation:"Wahyu 1:4, 1:11 — tujuh jemaah: Efesus, Smirna, Pergamus, Tiatira, Sardis, Filadelfia, Laodikia. [Wahyu 1:4]" }),
  NT3({ id:'q_l3_75', question:"Kisah Para Rasul pasal 2 menceritakan peristiwa?", options:["Pentakosta","Paskah","Khutbah Yesus","Pemujaan berhala"], correctAnswer:0, explanation:"Kisah 2:1-4 — Pentakosta. [Kisah 2:1-4]" }),
  // Epistles + General (25)
  NT3({ id:'q_l3_76', question:"'Aku dapat menyesuaikan diri dengan segala keadaan' terdapat dalam kitab?", options:["Roma","1 Korintus","Filipi","Galatia"], correctAnswer:2, explanation:"Filipi 4:12 — 'Aku tahu caranya hidup dalam kekurangan'. [Filipi 4:12]" }),
  NT3({ id:'q_l3_77', question:"Roma 8:28 'Semua hal bekerja bersama untuk kebaikan...'?", options:["Orang sempurna","Mereka yang mengasihi Allah","Mereka yang kaya","Pemimpin"], correctAnswer:1, explanation:"Roma 8:28 — 'untuk kebaikan mereka yang mengasihi Allah'. [Roma 8:28]" }),
  NT3({ id:'q_l3_78', question:"Surat Efesus membahas topik utama?", options:["Ibadat bait","Kasih Kristus dan kesatuan jemaah","Makanan halal","Hari Sabat"], correctAnswer:1, explanation:"Efesus 4:1-6 — kesatuan jemaah. [Efesus 4:1-6, 3:14-21]" }),
  NT3({ id:'q_l3_79', question:"1 Timotius 3:1-7 memberikan syarat untuk menjadi?", options:["Diakon","Uskup","Gembala sidang","Raja"], correctAnswer:1, explanation:"1 Timotius 3:1-7 — syarat menjadi pengawas (uskup). [1 Timotius 3:1-7]" }),
  NT3({ id:'q_l3_80', question:"1 Yohanes 4:8 mendefinisikan Allah sebagai?", options:["Kebenaran","Kasih","Roh","Cahaya"], correctAnswer:1, explanation:"1 Yohanes 4:8,16 — 'Allah adalah kasih'. [1 Yohanes 4:8]" }),
  NT3({ id:'q_l3_81', question:"Yesus berkata 'Akulah gembala yang baik' di kitab?", options:["Matius","Markus","Lukas","Yohanes"], correctAnswer:3, explanation:"Yohanes 10:11 — 'Akulah gembala yang baik'. [Yohanes 10:11, 10:14]" }),
  NT3({ id:'q_l3_82', question:"Surat 1 Petrus ditujukan kepada?", options:["Asia Barat","Sebaran Pontus, Galatia, Kapadokia, Asia, dan Bitinia","Mesir","Persia"], correctAnswer:1, explanation:"1 Petrus 1:1 — 'di Pontus, Galatia, Kapadokia, Asia, dan Bitinia'. [1 Petrus 1:1]" }),
  NT3({ id:'q_l3_83', question:"2 Tesalonika membahas?", options:["Hari Sabat","Kedatangan Kristus kedua kali","Makanan halal","Lokasi berhala"], correctAnswer:1, explanation:"2 Tesalonika 2:1-3 — kedatangan Tuhan kita Yesus Kristus. [2 Tesalonika 2:1-3]" }),
  NT3({ id:'q_l3_84', question:"Filemon ialah surat Paulus tentang hamba bernama?", options:["Onesimus","Timotius","Titus","Barnabas"], correctAnswer:0, explanation:"Filemon 1:10 — 'mengenai anakku Onesimus'. [Filemon 1:10, 1:16]" }),
  NT3({ id:'q_l3_85', question:"Titus 2:11 'Kasih setia Allah yang menyelamatkan semua orang telah nyata' merujuk kepada siapa?", options:["Hanya bangsa Israel","Hanya orang Yahudi","Semua orang","Hanya pemimpin"], correctAnswer:2, explanation:"Titus 2:11 — 'menyelamatkan semua orang'. [Titus 2:11-14]" }),
  NT3({ id:'q_l3_86', question:"Ibrani 11 menyenaraikan tokoh iman. Yang pertama ialah?", options:["Abraham","Habel","Nuh","Musa"], correctAnswer:1, explanation:"Ibrani 11:4 — 'Habel mempersembahkan korban yang lebih baik'. [Ibrani 11:4]" }),
  NT3({ id:'q_l3_87', question:"'Bintang pagi' dalam Wahyu adalah lambang?", options:["Keperkasaan Allah","Yesus sendiri","Para malaikat","Roh Kudus"], correctAnswer:1, explanation:"Wahyu 22:16 — 'Akulah bintang pagi yang cemerlang'. [Wahyu 22:16, 2:28]" }),
  NT3({ id:'q_l3_88', question:"Kemah Suci Musa terdiri dari berapa bagian utama?", options:["1","2 (Tempat Suci dan Tempat Mahakudus)","3","4"], correctAnswer:1, explanation:"Ibrani 9:1-3 — 'Kemah yang pertama' dan 'tempat yang paling dalam'. [Ibrani 9:1-7, Keluaran 26-27]" }),
  NT3({ id:'q_l3_89', question:"2 Yohanes panjangnya berapa ayat?", options:["13 ayat","21 ayat","Tiga pasal","Sepuluh ayat"], correctAnswer:0, explanation:"2 Yohanes mengandungi 13 ayat dalam 1 pasal — kitab paling pendek. [2 Yohanes 1:1-13]" }),
  NT3({ id:'q_l3_90', question:"Yudas membahas mempertahankan iman daripada?", options:["Guru-guru palsu","Penganiayaan Rom","Kekeringan","Kelaparan"], correctAnswer:0, explanation:"Yudas 1:3-4 — berjuang untuk iman yang disampaikan. [Yudas 1:3-4]" }),
  NT3({ id:'q_l3_91', question:"Yesus berkata 'Akulah pintu' untuk domba-domba di kitab?", options:["Matius 10","Yohanes 10","Lukas 12","Wahyu 3"], correctAnswer:1, explanation:"Yohanes 10:9 — 'Akulah pintu'. [Yohanes 10:9]" }),
  NT3({ id:'q_l3_92', question:"Perumpamaan tubuh dan anggota Paulus terdapat di?", options:["Roma 12","1 Korintus 12","Efesus 4","Galatia 3"], correctAnswer:1, explanation:"1 Korintus 12:12-27 — 'tubuh adalah satu dan banyak anggota'. [1 Korintus 12:12-27]" }),
  NT3({ id:'q_l3_93', question:"Ular yang ditinggikan oleh Musa di padang gurun (Bilangan 21) menjadi lambang?", options:["Kesembuhan","Salib Yesus","Roh jahat","Dosa"], correctAnswer:1, explanation:"Bilangan 21:8-9 — 'buatlah ular yang mudah terbang'. Yohanes 3:14 membandingkannya dengan Kristus. [Bilangan 21:8-9, Yohanes 3:14]" }),
  NT3({ id:'q_l3_94', question:"Khotbah di Bukit (Matius 5-7) bermula dengan?", options:["10 Perintah","Berbahagialah (Beatitudes)","Perumpamaan","Pengakuan iman"], correctAnswer:1, explanation:"Matius 5:1-12 — Khotbah di Bukit dimulai dengan 8 Beatitudes. [Matius 5:1-12]" }),
  NT3({ id:'q_l3_95', question:"Yesus menggunakan anak kecil sebagai contoh untuk menggambarkan?", options:["Kemurahan hati","Kerendahan hati dan iman yang sederhana","Pengetahuan","Pengorbanan"], correctAnswer:1, explanation:"Matius 18:2-4 — 'Jika kamu tidak bertobat dan menjadi seperti anak kecil'. [Matius 18:2-4]" }),
  NT3({ id:'q_l3_96', question:"Petrus menyangkal Yesus tiga kali tepat sebelum?", options:["Paskah","Ayam berkokok","Salib","Yesus ditangkap"], correctAnswer:1, explanation:"Lukas 22:60-61 — 'Pada waktu itu juga berkokoklah ayam'. [Lukas 22:60-61]" }),
  NT3({ id:'q_l3_97', question:"'Di mana hartamu berada, di situ juga hatimu berada' terdapat di?", options:["Yohanes 4","Matius 6","Lukas 12","Markus 10"], correctAnswer:1, explanation:"Matius 6:21 — 'Di mana hartamu berada, di situ juga hatimu berada'. [Matius 6:21]" }),
  NT3({ id:'q_l3_98', question:"Kabar baik pertama yang Yesus wartakan di Galilea ialah?", options:["Bertobatlah, Kerajaan Allah sudah dekat","Pergilah ke Bait Suci","Berikan sedekah","Jangan makan daging"], correctAnswer:0, explanation:"Matius 4:17 — 'Bertobatlah, sebab Kerajaan Surga sudah dekat'. [Matius 4:17]" }),
  NT3({ id:'q_l3_99', question:"Yerusalem dalam kitab Ratapan melambangkan?", options:["Kota asing","Israel sebagai anak Allah yang disengsarakan","Yesus di kayu salib","Semua manusia"], correctAnswer:1, explanation:"Ratapan 1:1-2 — Yerusalem bagaikan janda, anak Allah yang disengsarakan. [Ratapan 1:1-2]" }),
  OT3({ id:'q_l3_100', question:"Musa menaikkan ular tembaga di padang gurun pada peristiwa?", options:["Bilangan 21","Keluaran 16","Ulangan 8","Imamat 25"], correctAnswer:0, explanation:"Bilangan 21:8-9 — 'buatlah ular yang mudah terbang'. [Bilangan 21:8-9]" }),
];

// ============================================================
// LEVEL 4 (94 hard Bible questions)
//   Torah+Historical detail (24) + Wisdom+Prophets (20) + Gospels (25) +
//   Epistles+Revelation (15) + Deuterocanonical (10)
// ============================================================
const LEVEL4 = [
  // Torah + Historical detail (24)
  OT4({ id:'q_l4_1', question:"Pada hari ketujuh setelah penciptaan, Allah?", options:["Berehat dan memberkati hari itu","Menciptakan manusia lain","Menghancurkan taman","Meninggalkan bumi"], correctAnswer:0, explanation:"Kejadian 2:2-3 — 'Pada hari ketujuh Allah mengakhiri pekerjaan-Nya, dan Ia beristirahat. Lalu Allah memberkati hari ketujuh dan menguduskannya'. [Kejadian 2:2-3]" }),
  OT4({ id:'q_l4_2', question:"Berapa jumlah orang-orang percaya di kapal Nuh semasa banjir besar?", options:["4 orang (Nuh, isteri, 3 anak)","6 orang (Nuh, isteri, 3 anak + pasangan)","8 orang (Nuh, isteri, 3 anak + pasangan mereka)","10 orang"], correctAnswer:2, explanation:"1 Petrus 3:20 — 'Delapan orang dibawa dengan selamat melalui air'. Nuh dan isterinya, ketiga anak Sem, Ham, Yafet dan isteri-isteri mereka. [1 Petrus 3:20, Kejadian 7:7]" }),
  OT4({ id:'q_l4_3', question:"Berapa lama air bah melimpahi bumi?", options:["40 hari","100 hari","150 hari","365 hari"], correctAnswer:2, explanation:"Kejadian 7:24 — 'Air itu berlaku selama 150 hari di atas bumi'. Hujan berhenti hari ke-150. [Kejadian 7:24, 8:3]" }),
  OT4({ id:'q_l4_4', question:"Hawa diciptakan daripada?", options:["Tanah","Tulang rusuk Adam","Debu","Air"], correctAnswer:1, explanation:"Kejadian 2:21-23 — 'TUHAN Allah membangun dari tulang rusuk yang diambil-Nya dari Adam itu seorang perempuan'. [Kejadian 2:21-23]" }),
  OT4({ id:'q_l4_5', question:"Larangan utama di Taman Eden ialah tentang?", options:["Buah dari pohon kehidupan","Buah dari pohon pengetahuan tentang yang baik dan yang jahat","Berbicara dengan ular","Meninggalkan taman"], correctAnswer:1, explanation:"Kejadian 2:16-17 — 'Dari pohon pengetahuan tentang yang baik dan yang jahat janganlah engkau makan'. [Kejadian 2:16-17]" }),
  OT4({ id:'q_l4_6', question:"Pemanggilan Abraham berlaku di kota?", options:["Babel (Ur Kasdim)","Haran","Kanaan","Mesir"], correctAnswer:1, explanation:"Kejadian 12:1-4 — 'TUHAN berfirman kepada Abram: Pergilah dari negerimu'. Bermula di Haran. [Kejadian 12:1-4]" }),
  OT4({ id:'q_l4_7', question:"Yesus dipercayai adalah keturunan Abraham melalui?", options:["Ishak","Ismail","Eber","Nahor"], correctAnswer:0, explanation:"Matius 1:2, Kejadian 21:3 — Yesus keturunan Ishak. [Matius 1:2, Kejadian 21:3]" }),
  OT4({ id:'q_l4_8', question:"Ishak hampir dikorbankan oleh Abraham di gunung?", options:["Sinai","Moria","Horeb","Nebo"], correctAnswer:1, explanation:"Kejadian 22:2 — 'Ambillah anakmu yang единственный itu, Ishak, dan pergilah ke tanah Moria'. [Kejadian 22:2]" }),
  OT4({ id:'q_l4_9', question:"Yakub bermimpi tentang tangga yang naik ke surga di?", options:["Hebron","Betel","Beer-Syeba","Mahanaim"], correctAnswer:1, explanation:"Kejadian 28:19 — 'Ia menamakan tempat itu Betel'. Tangga bermimpi di Betel. [Kejadian 28:10-19]" }),
  OT4({ id:'q_l4_10', question:"Anak Yakub yang menjadi leluhur raja-raja Israel ialah?", options:["Ruben","Yusuf","Yehuda","Benyamin"], correctAnswer:2, explanation:"Kejadian 49:10 — 'Tongkat kekuasaan tidak akan beranjak dari Yehuda'. Mesias akan datang dari Yehuda. [Kejadian 49:10]" }),
  OT4({ id:'q_l4_11', question:"Yusuf dijual oleh saudara-saudaranya kepada siapa?", options:["Firaun","Orang Ismael","Orang Midian","Raja Babel"], correctAnswer:1, explanation:"Kejadian 37:25-28 — saudara-saudara Yusuf menjualnya kepada orang Ismael. [Kejadian 37:25-28]" }),
  OT4({ id:'q_l4_12', question:"Nama yang diberikan Firaun kepada Yusuf di Mesir ialah?", options:["Zafnat-Pa'neah","Abraham","Nakhur","Potifar"], correctAnswer:0, explanation:"Kejadian 41:45 — 'Firaun menamai Yusuf: Zafnat-Pa'neah'. [Kejadian 41:45]" }),
  OT4({ id:'q_l4_13', question:"Musa membina tabut untuk menyimpan?", options:["Tabut Perjanjian (loh batu 10 Perintah)","Manna","Tongkat Harun","Segala perkakas"], correctAnswer:0, explanation:"Keluaran 25:10-22 — Musa membuat Tabut Perjanjian untuk menyimpan loh batu. [Keluaran 25:10-22]" }),
  OT4({ id:'q_l4_14', question:'Pada waktu Musa menerima 10 Perintah, gunung Sinai bergetar dan apa yang turun?', options:["Hujan","Api","Salju","Batu"], correctAnswer:1, explanation:"Keluaran 19:18 — 'Seluruh gunung Sinai berasap, sebab TUHAN turun di atasnya dalam api'. [Keluaran 19:18]" }),
  OT4({ id:'q_l4_15', question:"Yang bukan termasuk 10 Perintah ialah?", options:["Jangan membunuh","Jangan mencuri","Jangan menyembah berhala","Jangan makan daging khinzir"], correctAnswer:3, explanation:"Keluaran 20:1-17 — 10 Perintah tidak termasuk pantang daging khinzir (larangan Leviticus 11). [Keluaran 20:1-17]" }),
  OT4({ id:'q_l4_16', question:"Hari Sabat hari ketujuh diperintahkan untuk?", options:["Bekerja keras","Berhenti bekerja dan menguduskan hari itu","Menyembah berhala","Mengumpulkan manna"], correctAnswer:1, explanation:"Keluaran 20:8-11 — 'Ingatlah untuk menguduskan hari Sabat, jangan melakukan pekerjaan'. [Keluaran 20:8-11]" }),
  OT4({ id:'q_l4_17', question:"Yosua memimpin bangsa Israel menyeberangi sungai?", options:["Nil","Yordan","Eufrat","Tigris"], correctAnswer:1, explanation:"Yosua 3:14-17 — bangsa Israel menyeberangi Sungai Yordan. [Yosua 3:14-17]" }),
  OT4({ id:'q_l4_18', question:"Daud mengalahkan Goliat dengan senjata apakah?", options:["Pedang","Senapan","Pengungkit dan batu","Busur"], correctAnswer:2, explanation:"1 Samuel 17:49-50 — Daud memasukkan tangannya dalam kantongnya, mengambil sebuah batu dan melemparkannya. [1 Samuel 17:49-50]" }),
  OT4({ id:'q_l4_19', question:"Goliat berasal dari kota?", options:["Yerusalem","Gat","Asdod","Betlehem"], correctAnswer:1, explanation:"1 Samuel 17:4 — 'Goliat dari Gat'. Goliat ialah raksasa dari Gat. [1 Samuel 17:4]" }),
  OT4({ id:'q_l4_20', question:"Salomo membangun Bait Suci di Yerusalem pada tahun ke berapa pemerintahannya?", options:["Tahun pertama","Tahun kedua","Tahun keempat","Tahun ketujuh"], correctAnswer:2, explanation:"1 Raja-raja 6:1 — 'Dalam tahun keempat ratus delapan ratus, yang kedua bulan Zif, pada tahun keempat pemerintahannya'. [1 Raja-raja 6:1]" }),
  OT4({ id:'q_l4_21', question:"Pada zaman Raja Ahab, nabi Elia berhadapan dengan?", options:["400 nabi Baal","300 nabi Asherah","500 imam","1000 penyembah"], correctAnswer:0, explanation:"1 Raja-raja 18:19 — Elia mengumpulkan 450 nabi Baal di Gunung Karmel. [1 Raja-raja 18:19]" }),
  OT4({ id:'q_l4_22', question:"Danieli sahabat Daniel di Babel ialah?", options:["Yusuf","Sadrakh, Mesakh, Abednego","Yeremia","Hilkia"], correctAnswer:1, explanation:"Daniel 1:6-7 — Daniel, Hanania, Misael, Azaria. Raja Babel menamai mereka Beltsazar, Sadrakh, Mesakh, Abednego. [Daniel 1:6-7, 3:19-30]" }),
  OT4({ id:'q_l4_23', question:"Sadrakh, Mesakh, Abednego dibuang ke dalam?", options:["Laut","Gua singa","Dapur api","Sumur"], correctAnswer:2, explanation:"Daniel 3:19-23 — raja Nebukadnezar memerintahkan mereka dibakar dalam dapur api yang menyala-nyala. [Daniel 3:19-23]" }),
  OT4({ id:'q_l4_24', question:"Setelah kejatuhan Yerusalem, bangsa Yahudi dibuang ke?", options:["Mesir","Babel","Persia","Roma"], correctAnswer:1, explanation:"2 Raja-raja 24:14, 2 Tawarikh 36:20 — Yehoyakhin dan bangsanya dibuang ke Babel. [2 Raja-raja 24:14]" }),
  // Wisdom + Prophets detail (20)
  OT4({ id:'q_l4_25', question:"Mazmur Daud yang dikutip Yesus di kayu salib ialah?", options:["Mazmur 22","Mazmur 1","Mazmur 150","Mazmur 119"], correctAnswer:0, explanation:"Matius 27:46 — 'Yesus berseru dengan suara nyaring: Eli, Eli, lama sabakhtani?' dari Mazmur 22:2. [Matius 27:46, Mazmur 22:2]" }),
  OT4({ id:'q_l4_26', question:"'TUHAN adalah gembalaku' mula frasa?", options:["Mazmur 1","Mazmur 22","Mazmur 23","Mazmur 24"], correctAnswer:2, explanation:"Mazmur 23:1 — 'Tuhan adalah gembalaku, takkan kekurangan aku'. [Mazmur 23:1]" }),
  OT4({ id:'q_l4_27', question:"Mazmur yang dipakai dalam pujian Maria (Magnificat) di?", options:["1 Samuel 2","Mazmur 23","Yesaya 11","Matius 5"], correctAnswer:0, explanation:"Lukas 1:46-55 — Maria bermazmur seperti Hana dalam 1 Samuel 2:1-10. [Lukas 1:46-55, 1 Samuel 2:1-10]" }),
  OT4({ id:'q_l4_28', question:"'Berbahagialah orang yang tidak berjalan dalam nasihat orang fasik' adalah mula frasa?", options:["Mazmur 1","Amsal 1","Pengkhotbah 12","Yesaya 1"], correctAnswer:0, explanation:"Mazmur 1:1 — 'Berbahagialah orang yang tidak berjalan dalam nasihat orang fasik'. [Mazmur 1:1]" }),
  OT4({ id:'q_l4_29', question:"Tokoh-tokoh yang datang kepada Ayub untuk menghibur ialah?", options:["Elifas, Bildad, Zofar","Abraham, Ishak, Yakub","Musa, Harun, Miryam","Yusuf, Simeon, Lewi"], correctAnswer:0, explanation:"Ayub 2:11 — ketiga teman Ayub: Elifas orang Teman, Bildad orang Suah, Zofar orang Naama. [Ayub 2:11]" }),
  OT4({ id:'q_l4_30', question:"Ibrani 'Qohelet' (pengkhutbah/pemikir) adalah nama lain untuk?", options:["Salomo","Daud","Yesaya","Daniel"], correctAnswer:0, explanation:"Pengkhotbah 1:1 — 'Perkataan-perkataan Pengkhotbah, anak Daud, raja di Yerusalem'. Salomo tradisi. [Pengkhotbah 1:1]" }),
  OT4({ id:'q_l4_31', question:"Yesaya menubuatkan tentang Mesias yang akan dilahirkan dari seorang dara. Dalam bahasa Ibrani perkataan 'almah' bermaksud?", options:["Anak muda perempuan (bukan perkahwinan)","Isteri","Janda","Pekerja"], correctAnswer:0, explanation:"Yesaya 7:14 — perkataan Ibrani 'almah' bermaksud 'gadis muda', bukan perkataan yang spesifik 'perawan'. [Yesaya 7:14]" }),
  OT4({ id:'q_l4_32', question:"Yesaya menubuatkan tentang 'Hamba yang Menderita' pada bab berapa?", options:["Yesaya 53","Yesaya 7","Yesaya 11","Yesaya 9"], correctAnswer:0, explanation:"Yesaya 52:13-53:12 — Hamba YHWH yang menderita. [Yesaya 52:13-53:12]" }),
  OT4({ id:'q_l4_33', question:"Kata Ibrani 'YHWH' ialah nama Allah yang bermaksud?", options:["Aku Ada (I AM)","Bapa","Tuhan","Pencipta"], correctAnswer:0, explanation:"Keluaran 3:14 — 'AKU ADALAH AKU'. YHWH = 'Yahweh' = 'Aku adalah'. [Keluaran 3:14]" }),
  OT4({ id:'q_l4_34', question:"Yeremia menulis kitab?", options:["Hanya kitab Yeremia","Kitab Yeremia dan Ratapan","Hanya kitab Ratapan","Kitab Pengkhotbah"], correctAnswer:1, explanation:"Yeremia menulis kitab Yeremia (52 pasal) dan Ratapan (5 pasal). [Yeremia 1-52, Ratapan 1-5]" }),
  OT4({ id:'q_l4_35', question:"Kitab Yehezkiel menceritakan penglihatan tentang?", options:["Kehancuran Bait Suci","Kereta gandar Ilahi, tulang-tulang kering, sungai baru","Peperangan","Raja-raja Israel"], correctAnswer:1, explanation:"Yehezkiel 1 (kendaraan ilahi), 37 (tulang kering), 47 (sungai dari Bait Suci). [Yehezkiel 1, 37, 47]" }),
  OT4({ id:'q_l4_36', question:"Daniel menafsirkan tulisan di dinding untuk raja?", options:["Koresy","Belsyazar","Daud","Hiskia"], correctAnswer:1, explanation:"Daniel 5:1-31 — 'Mene, mene, tekel, ufarsin' ditafsirkan Daniel untuk raja Belsyazar. [Daniel 5:1-31]" }),
  OT4({ id:'q_l4_37', question:"Kitab Tawarikh (1 & 2) banyak mengulangi isi kitab?", options:["Daniel","Samuel dan Raja-raja","Amsal","Matius"], correctAnswer:1, explanation:"1 Tawarikh mengulangi 1-2 Samuel, 2 Tawarikh mengulangi 1-2 Raja-raja — kitab-kitab sejarah paralel. [1 Tawarikh, 2 Tawarikh]" }),
  OT4({ id:'q_l4_38', question:"Nabi Yunus setelah berdoa di perut ikan berapa hari ia dimuntahkan di darat?", options:["1 hari","2 hari","3 hari","7 hari"], correctAnswer:2, explanation:"Yunus 2:1 — 'Yunus berada dalam perut ikan itu selama tiga hari dan tiga malam'. [Yunus 2:1, Matius 12:40]" }),
  OT4({ id:'q_l4_39', question:"'Aku bersukacita atas firman-Mu seperti orang yang mendapat jarahan banyak' terdapat di?", options:["Mazmur 119","Amsal 16","Yesaya 61","Yeremia 17"], correctAnswer:0, explanation:"Mazmur 119:162 — 'Aku bersukacita atas janji-Mu seperti orang yang menemukan jarahan banyak'. [Mazmur 119:162]" }),
  OT4({ id:'q_l4_40', question:"'Takutlah akan TUHAN' adalah permulaan hikmat menurut?", options:["Amsal 9:10","Matius 5","Yesaya 1","Ratapan 3"], correctAnswer:0, explanation:"Amsal 9:10 — 'Permulaan hikmat adalah takut akan TUHAN'. [Amsal 9:10]" }),
  OT4({ id:'q_l4_41', question:"'Aku tertidur, lalu bermimpi...' merupakan frasa dari kitab?", options:["Daniel","1 Raja-raja","2 Tawarikh","Wahyu"], correctAnswer:0, explanation:"Daniel 2:1 — 'Pada tahun kedua pemerintahan Nebukadnezar, bermimpilah Nebukadnezar mimpi'. Daniel menafsirkan. [Daniel 2:1-49]" }),
  OT4({ id:'q_l4_42', question:"Roh Kudus yang keluar dalam Kitab Suci yang menciptakan alam dikaitkan dengan?", options:["Kejadian 1:2","Mazmur 33","Matius 3","Kisah 2"], correctAnswer:0, explanation:"Kejadian 1:2 — 'Ruh Allah melayang-layang di atas permukaan air'. Penciptaan. [Kejadian 1:2]" }),
  OT4({ id:'q_l4_43', question:"Tujuh kata Salomo yang tercatat dalam Pengkhotbah pasal 3 adalah gambaran tentang?", options:["Kejayaan","Waktu yang sesuai untuk segala sesuatu","Kekuasaan","Kemiskinan"], correctAnswer:1, explanation:"Pengkhotbah 3:1-8 — 'Untuk segala sesuatu ada waktunya'. [Pengkhotbah 3:1-8]" }),
  OT4({ id:'q_l4_44', question:"Mazmur yang paling pendek (2 ayat) dalam Alkitab ialah?", options:["Mazmur 117","Mazmur 150","Mazmur 1","Mazmur 119"], correctAnswer:0, explanation:"Mazmur 117:1-2 — hanya dua ayat, mazmur terpendek. [Mazmur 117:1-2]" }),
  // Gospels deep (25)
  NT4({ id:'q_l4_45', question:"Berbahagialah yang miskin di hadapan Allah — ini adalah?", options:["Beatitudes pertama","Beatitudes kelapan","Perumpamaan","Suruhan rasul"], correctAnswer:0, explanation:"Matius 5:3 — 'Berbahagialah orang yang miskin di hadapan Allah, karena mereka memiliki Kerajaan Surga'. Beatitudes pertama. [Matius 5:3]" }),
  NT4({ id:'q_l4_46', question:"Berapa banyak 'Berbahagialah' (Beatitudes) dalam Khotbah di Bukit?", options:["5","7","8","10"], correctAnswer:2, explanation:"Matius 5:3-10 — lapan Beatitudes. [Matius 5:3-10]" }),
  NT4({ id:'q_l4_47', question:"Yesus berkata 'Akulah roti hidup' di kitab?", options:["Matius 6","Yohanes 6","Matius 26","1 Korintus 11"], correctAnswer:1, explanation:"Yohanes 6:35,48 — 'Aku adalah roti hidup'. [Yohanes 6:35, 6:48]" }),
  NT4({ id:'q_l4_48', question:"Yesus berkata 'Akulah terang dunia' di kitab?", options:["Matius","Markus","Lukas","Yohanes"], correctAnswer:3, explanation:"Yohanes 8:12 — 'Akulah terang dunia'. [Yohanes 8:12]" }),
  NT4({ id:'q_l4_49', question:"Yesus berkata 'Akulah pintu' di kitab?", options:["Matius 10","Yohanes 10","Lukas 12","Wahyu 3"], correctAnswer:1, explanation:"Yohanes 10:9 — 'Akulah pintu'. [Yohanes 10:9]" }),
  NT4({ id:'q_l4_50', question:"'Akulah pokok anggur dan kamulah cabang-cabangnya' terdapat di?", options:["Yohanes 15","Matius 12","Lukas 22","Wahyu 14"], correctAnswer:0, explanation:"Yohanes 15:5 — 'Akulah pokok anggur'. [Yohanes 15:5]" }),
  NT4({ id:'q_l4_51', question:"Yesus berkata 'Aku dan Bapa adalah satu' di kitab?", options:["Matius","Markus","Lukas","Yohanes"], correctAnswer:3, explanation:"Yohanes 10:30 — 'Aku dan Bapa adalah satu'. [Yohanes 10:30]" }),
  NT4({ id:'q_l4_52', question:"'Akulah kebangkitan dan hidup' terdapat di?", options:["Yohanes 11","Matius 5","Lukas 24","Kisah 2"], correctAnswer:0, explanation:"Yohanes 11:25 — 'Akulah kebangkitan dan hidup'. [Yohanes 11:25]" }),
  NT4({ id:'q_l4_53', question:"'Akulah jalan, kebenaran dan hidup' terdapat di?", options:["Matius 6","Yohanes 14","Yohanes 8","Kisah 9"], correctAnswer:1, explanation:"Yohanes 14:6 — 'Akulah jalan, dan kebenaran, dan hidup'. [Yohanes 14:6]" }),
  NT4({ id:'q_l4_54', question:"'Akulah gembala yang baik' terdapat di?", options:["Matius","Markus","Lukas","Yohanes"], correctAnswer:3, explanation:"Yohanes 10:11 — 'Akulah gembala yang baik'. [Yohanes 10:11]" }),
  NT4({ id:'q_l4_55', question:"Saudara perempuan Marta dan Maria yang dibangkitkan Yesus ialah?", options:["Lazarus","Yusuf","Simon","Zakeus"], correctAnswer:0, explanation:"Yohanes 11:1-44 — Lazarus, saudara Marta dan Maria di Betania. [Yohanes 11:1-44]" }),
  NT4({ id:'q_l4_56', question:"Yesus pertama kali membasuh kaki murid-murid-Nya pada?", options:["Paskah","Perjamuan Terakhir","Pentakosta","Minggu Palma"], correctAnswer:1, explanation:"Yohanes 13:1-15 — Yesus membasuh kaki murid pada Perjamuan Terakhir. [Yohanes 13:1-15]" }),
  NT4({ id:'q_l4_57', question:"Yesus berkata terdapat berapa bilik (mansion) dalam rumah Bapa?", options:["Sedikit","Satu","Banyak","Tiada"], correctAnswer:2, explanation:"Yohanes 14:2 — 'Di rumah Bapa-Ku banyak tempat tinggal'. [Yohanes 14:2]" }),
  NT4({ id:'q_l4_58', question:"Perumpamaan talenta menggambarkan?", options:["Penggunaan amanah yang setia","Kejahilan orang bodoh","Kerajaan Bait Suci","Pengembala domba"], correctAnswer:0, explanation:"Matius 25:14-30 — perumpamaan talenta menekankan penggunaan amanah yang setia. [Matius 25:14-30]" }),
  NT4({ id:'q_l4_59', question:"Perumpamaan anak yang hilang dalam Lukas 15 mengandungi tokoh?", options:["Bapa dan dua anak","Tuhan dan hamba","Raja dan pengemis","Gembala dan biri-biri"], correctAnswer:0, explanation:"Lukas 15:11-32 — bapa dengan dua orang anak (yang hilang dan yang sulung). [Lukas 15:11-32]" }),
  NT4({ id:'q_l4_60', question:"Perumpamaan orang Samaria yang baik mengisahkan tentang?", options:["Sesiapa yang menunjukkan belas kasihan","Orang yang berzakat","Orang kaya","Orang Farisi"], correctAnswer:0, explanation:"Lukas 10:33-37 — perumpamaan Samaria yang baik untuk menjelaskan 'sesiapa yang menunjukkan belas kasihan'. [Lukas 10:33-37]" }),
  NT4({ id:'q_l4_61', question:"Sermon di Bukit Yesus mengandungi?", options:["Beatitudes, Doa Bapa Kami, hikmat praktis","10 Perintah","Riwayat Isa","Mazmur"], correctAnswer:0, explanation:"Matius 5-7 — Sermon di Bukit mengandungi Beatitudes, Doa Bapa Kami, hikmat praktis. [Matius 5-7]" }),
  NT4({ id:'q_l4_62', question:"Yesus menyembuhkan orang buta sejak lahir dengan?", options:["Menyentuh","Meludah dan membuat lumpur, menyapukan ke mata","Hanya mengucapkan kata","Berdoa dari jauh"], correctAnswer:1, explanation:"Yohanes 9:6-7 — 'Yesus meludah ke tanah, membuat lumpur dengan air liur-Nya, dan melumasinya ke mata orang itu'. [Yohanes 9:6-7]" }),
  NT4({ id:'q_l4_63', question:"Lima ribu orang makan dan kenyang dengan berapa roti dan ikan?", options:["3 roti, 2 ikan","5 roti, 2 ikan","7 roti, 5 ikan","12 roti"], correctAnswer:1, explanation:"Matius 14:17-21 — 'Di sini ada lima roti dan dua ikan'. [Matius 14:17-21]" }),
  NT4({ id:'q_l4_64', question:"Yesus berjalan di atas?", options:["Tanah","Udara","Air","Api"], correctAnswer:2, explanation:"Matius 14:25 — Yesus berjalan di atas air. [Matius 14:25]" }),
  NT4({ id:'q_l4_65', question:"Khemah Suci yang Yesus masuki (setelah naik ke surga) ialah?", options:["Bait Suci Yerusalem","Kemah pertemuan di surga","Kuil Rom","Synagogue"], correctAnswer:1, explanation:"Ibrani 8:1-2 — Yesus masuk ke dalam Kemah Pertemuan yang besar di surga. [Ibrani 8:1-2, 9:11-24]" }),
  NT4({ id:'q_l4_66', question:"Yesus berdoa di Taman Getsemani dengan tiga murid?", options:["Petrus, Yakobus, Yohanes","Petrus, Andreas, Yakobus","Tomas, Yakobus, Yohanes","Simon, Andreas, Yohanes"], correctAnswer:0, explanation:"Matius 26:36-37 — Yesus membawa Petrus, Yakobus, dan Yohanes bersamanya. [Matius 26:36-37]" }),
  NT4({ id:'q_l4_67', question:"Petrus, Yakobus, dan Yohanes melihat dua tokoh Musa dan Elia bersama Yesus di?", options:["Bukit Zaitun","Gunung Transfigurasi","Taman Getsemani","Bukit Sinai"], correctAnswer:1, explanation:"Matius 17:1-8 — transfigurasi di gunung tinggi. [Matius 17:1-8]" }),
  NT4({ id:'q_l4_68', question:"Yesus berkata 'Akulah...' tujuh kali dalam Injil Yohanes. Jumlah sebenar ialah?", options:["5 kali","7 kali","9 kali","10 kali"], correctAnswer:1, explanation:"7 'Akulah' (ego eimi) dalam Injil Yohanes: roti hidup, terang, pintu, gembala, kebangkitan, jalan, pokok anggur. [Yohanes 6:35, 8:12, 10:9, 10:11, 11:25, 14:6, 15:5]" }),
  NT4({ id:'q_l4_69', question:"Dalam Khotbah di Bukit, Yesus berkata 'Berbahagialah orang yang membawa perdamaian, kerana mereka akan disebut anak-anak Allah' ialah Beatitudes ke berapa?", options:["Ke-5","Ke-6","Ke-7","Ke-8"], correctAnswer:2, explanation:"Matius 5:9 — 'Berbahagialah orang yang membawa perdamaian'. Beatitudes ketujuh. [Matius 5:9]" }),
  // Epistles + Revelation (15)
  NT4({ id:'q_l4_70', question:"1 Korintus 13:13 'Demikianlah tinggal ketiga hal ini: iman, pengharapan, dan kasih. Yang paling besar ialah?'", options:["Iman","Pengharapan","Kasih","Kesabaran"], correctAnswer:2, explanation:"1 Korintus 13:13 — 'Yang paling besar di antaranya ialah kasih'. [1 Korintus 13:13]" }),
  NT4({ id:'q_l4_71', question:"Buah Roh Kudus (Galatia 5:22-23) terdiri dari berapa sifat?", options:["7","8","9","12"], correctAnswer:2, explanation:"Galatia 5:22-23 — 'Kasih, sukacita, damai sejahtera, kesabaran, kemurahan, kebaikan, kesetiaan, kelemahlembutan, penguasaan diri'. 9 sifat. [Galatia 5:22-23]" }),
  NT4({ id:'q_l4_72', question:"Mail of God (Ephesians 6) berisi lengkap berapa senjata rohani?", options:["5","6","7","8"], correctAnswer:2, explanation:"Efesus 6:14-17 — ikat pinggang, dada, kaki, perisai, ketopong, pedang Roh. 6 tetapi ditambah 'doa' = 7 lengkap. [Efesus 6:14-17]" }),
  NT4({ id:'q_l4_73', question:"Filipi 2:6-11 merupakan himne tentang?", options:["Kasih Allah","Kerendahan hati dan peninggian Kristus","Kedatangan Kristus","Tubuh Kristus"], correctAnswer:1, explanation:"Filipi 2:6-11 — 'Ia telah merendahkan diri'. Hymn Kristologi tinggi. [Filipi 2:6-11]" }),
  NT4({ id:'q_l4_74', question:"Ibrani 11:1 mendefinisikan iman sebagai?", options:["Keyakinan tentang apa yang tidak kelihatan","Pengharapan akan keselamatan","Perbuatan","Doa"], correctAnswer:0, explanation:"Ibrani 11:1 — 'Iman adalah kepastian tentang apa yang diharapkan, bukti tentang hal-hal yang tidak kelihatan'. [Ibrani 11:1]" }),
  NT4({ id:'q_l4_75', question:"Yakobus 1:2-3 mengajarkan untuk bersukacita dalam?", options:["Berkah","Pencubaan","Kesedihan","Kemurahan"], correctAnswer:1, explanation:"Yakobus 1:2-3 — 'Berilah sukacita apabila kamu jatuh ke dalam berbagai-bagai pencobaan'. [Yakobus 1:2-3]" }),
  NT4({ id:'q_l4_76', question:"1 Petrus 2:9 menyebut umat Allah sebagai?", options:["Kekasih Allah","Imamat yang rajani, bangsa yang kudus","Anak-anak","Pemimpin"], correctAnswer:1, explanation:"1 Petrus 2:9 — 'Kamulah bangsa yang terpilih, imamat yang rajani, bangsa yang kudus'. [1 Petrus 2:9]" }),
  NT4({ id:'q_l4_77', question:"Wahyu 6 menampilkan berapa orang berkuda (Four Horsemen)?", options:["2","3","4","6"], correctAnswer:2, explanation:"Wahyu 6:1-8 — empat orang berkuda: kemenangan, peperangan, kelaparan, kematian. [Wahyu 6:1-8]" }),
  NT4({ id:'q_l4_78', question:"Kitab Wahyu menyebut angka 144,000. Angka ini bermaksud?", options:["Hanya 144,000 sahaja yang selamat","Umat Allah yang disegel (12 suku x 12.000)","Jumlah malaikat","Jumlah gereja"], correctAnswer:1, explanation:"Wahyu 7:4 — 'Aku mendengar jumlah mereka yang telah ditandai: seratus empat puluh empat ribu'. 12 suku Israel x 12,000. [Wahyu 7:4]" }),
  NT4({ id:'q_l4_79', question:"Haiwan (binatang buas) yang keluar dari laut dalam Wahyu 13 ialah?", options:["Singa","Naga","Binatang dengan tujuh kepala dan sepuluh tanduk","Burung"], correctAnswer:2, explanation:"Wahyu 13:1 — 'Aku melihat seekor binatang keluar dari laut, ia memiliki tujuh kepala dan sepuluh tanduk'. [Wahyu 13:1-10]" }),
  NT4({ id:'q_l4_80', question:"Yerusalem Baru dalam Wahyu 21 adalah?", options:["Kota besar dengan Bait Suci","Isteri Anak Domba","Binatang","Malaikat"], correctAnswer:1, explanation:"Wahyu 21:9-10 — 'Marilah ke sini, aku akan menunjukkan kepadamu pengantin perempuan, isteri Anak Domba'. [Wahyu 21:9-10]" }),
  NT4({ id:'q_l4_81', question:"'Bapa kami yang di surga' adalah pembukaan?", options:["Doa Bapa Kami (Matius 6)","Mazmur 23","Yesaya 6","Matius 28"], correctAnswer:0, explanation:"Matius 6:9 — 'Doa Bapa Kami'. [Matius 6:9-13]" }),
  NT4({ id:'q_l4_82', question:"Roh Kudus dalam Injil Yohanes disebut sebagai?", options:["Penolong (Paraclete)","Roh jahat","Nur","Binatang"], correctAnswer:0, explanation:"Yohanes 14:26 — 'Ia akan mengutus Penolong (Paracletos)'. [Yohanes 14:26]" }),
  NT4({ id:'q_l4_83', question:"Yesus adalah 'Anak Domba Allah' yang menghilangkan dosa dunia — kata Yohanes Pembaptis di?", options:["Yohanes 1:29","Matius 3","Lukas 1","Wahyu 5"], correctAnswer:0, explanation:"Yohanes 1:29 — 'Lihatlah Anak Domba Allah, yang menghapus dosa dunia'. [Yohanes 1:29]" }),
  NT4({ id:'q_l4_84', question:"Nama 'Yesus' bermaksud dalam bahasa Ibrani?", options:["Tuhan menyelamatkan","Allah bersama","Anak Domba","Raja"], correctAnswer:0, explanation:"Matius 1:21 — 'Engkau akan menamakan dia Yesus, karena Ia akan menyelamatkan umat-Nya dari dosa mereka'. [Matius 1:21]" }),
  // Deuterocanonical (10)
  OT4({ id:'q_l4_85', question:"Tobit ialah seorang Yahudi di pembuangan yang buta. Siapa malaikat yang menemani anaknya Tobias?", options:["Rafael","Mikha'el","Gabriel","Uriel"], correctAnswer:0, explanation:"Tobit 5:16 — 'Aku ialah Rafael'. [Tobit 5:16]" }),
  OT4({ id:'q_l4_86', question:"Yudit membunuh Holofernes — jeneral empayar mana?", options:["Asyur (Nebukadnezar)","Persia","Yunani","Roma"], correctAnswer:0, explanation:"Yudit 1:1 — Nebukadnezar, raja Asyur. [Yudit 1:1, 13:1-10]" }),
  OT4({ id:'q_l4_87', question:"Ratu Ester mendedahkan dirinya kepada raja pada?", options:["Hari pertama bulan Teber","Hari keempat bulan","Hari ketujuh","Hari terakhir"], correctAnswer:0, explanation:"Ester 2:16 — 'Pada hari ketujuh bulan ke sepuluh, yaitu bulan Teber'. [Ester 2:16, 5:1]" }),
  OT4({ id:'q_l4_88', question:"'Tambahan Ester' merangkumi bagaimana ayat?", options:["5 bab tambahan (A-F)","1 pasal tambahan","3 bab tambahan","Tiada tambahan"], correctAnswer:0, explanation:"Tambahan Ester (A-F) — kumpulan enam tambahan Katolik yang menambahkan konteks keagamaan kepada Kitab Ester. [Ester (Tambahan) A-F]" }),
  OT4({ id:'q_l4_89', question:"'Kebijaksanaan' (Wisdom) dihimpun oleh siapa?", options:["Salomo","Daud","Yesaya","Yeremia"], correctAnswer:0, explanation:"Kebijaksanaan 7:1-7 — Salomon berdoa untuk hikmat. [Kebijaksanaan 7:1-7]" }),
  OT4({ id:'q_l4_90', question:"Sirakh (Ecclesiasticus) pasal 1 ayatnya berkata 'Permulaan hikmat ialah'?", options:["Takut akan TUHAN","Menahan diri","Menjadi kaya","Berkorban"], correctAnswer:0, explanation:"Sirakh 1:14 — 'Permulaan hikmat ialah takut akan TUHAN'. [Sirakh 1:14]" }),
  OT4({ id:'q_l4_91', question:"Kitab Barukh ialah kitab yang dikaitkan dengan?", options:["Yeremia","Yesaya","Ezekiel","Daniel"], correctAnswer:0, explanation:"Barukh 1:1 — 'kata-kata kitab yang ditulis oleh Barukh anak Neria'. Sahabat Yeremia. [Barukh 1:1]" }),
  OT4({ id:'q_l4_92', question:"Kitab 1 Makabe menceritakan peristiwa pada abad?", options:["Abad ke-2 SM","Abad ke-3 SM","Abad ke-4 SM","Abad ke-5 SM"], correctAnswer:0, explanation:"1 Makabe 1:1-9 — peristiwa Revolusi Makabe berlaku sekitar 167-160 SM (abad ke-2 SM). [1 Makabe 1:1-9]" }),
  OT4({ id:'q_l4_93', question:"Kitab 2 Makabe bermula dengan dua surat kepada?", options:["Orang Yahudi di Mesir","Orang Yahudi di Babel","Umat Kristen","Raja-raja"], correctAnswer:0, explanation:"2 Makabe 1:1-9 — dua surat kepada orang Yahudi di Mesir. [2 Makabe 1:1-9]" }),
  OT4({ id:'q_l4_94', question:"Kitab Daniel 'Tambahan Susana dan Para Penatua' menceritakan?", options:["Seorang wanita diberkati meskipun dipenjarakan","Naga di Babel","Empat kerajaan","Mimpi Nebukadnezar"], correctAnswer:0, explanation:"Daniel Tambahan 13 (Susana) — Susana yang difitnah oleh dua orang penatua. [Daniel (Susana) 13:1-64]" }),
];

console.log(`Level 4 entries ready: ${LEVEL4.length}`);

// ============================================================
// LEVEL 5 (100 hardest Bible questions)
//   Book-level facts (20) + Hebrew-Greek terminology (15) + Number symbolism (10) +
//   'Who said this?' (15) + Cross-testament typology (15) + Cultic/liturgical specifics (15) +
//   Eschatology (10)
// ============================================================
const LEVEL5 = [
  // Book-level facts (20)
  OT5({ id:'q_l5_1', question:"Kitab terpanjang dalam Alkitab (Perjanjian Lama dan Baru) ialah?", options:["Mazmur","Yesaya","Kejadian","Matius"], correctAnswer:1, explanation:"Yesaya 66 pasal. [Yesaya 1-66]" }),
  OT5({ id:'q_l5_2', question:"Kitab yang paling pendek dalam Perjanjian Lama ialah?", options:["Obaja","Yunus","Habakuk","Yoel"], correctAnswer:0, explanation:"Obaja 21 ayat — kitab terpendek dalam Perjanjian Lama. [Obaja 1-21]" }),
  OT5({ id:'q_l5_3', question:"Kitab yang paling pendek dalam Perjanjian Baru ialah?", options:["2 Yohanes","Filemon","Yudas","Obaja"], correctAnswer:0, explanation:"2 Yohanes 13 ayat — kitab terpendek dalam Perjanjian Baru. [2 Yohanes 1-13]" }),
  OT5({ id:'q_l5_4', question:"Kitab pertama dalam Perjanjian Lama ialah?", options:["Kejadian","Yesaya","Matius","Mazmur"], correctAnswer:0, explanation:"Kejadian adalah kitab pertama kanun Alkitab. [Kejadian 1:1]" }),
  OT5({ id:'q_l5_5', question:"Kitab terakhir dalam Perjanjian Lama (kanon Katolik) ialah?", options:["Maleakhi","Yesaya","Daniel","Barukh"], correctAnswer:0, explanation:"Maleakhi adalah kitab terakhir Perjanjian Lama dalam susunan kanon Katolik. [Maleakhi 1-3]" }),
  NT5({ id:'q_l5_6', question:"Kitab terakhir dalam Alkitab ialah?", options:["Wahyu","Matius","Ibrani","Kisah"], correctAnswer:0, explanation:"Wahyu kepada Yohanes — kitab terakhir Perjanjian Baru. [Wahyu 1:1]" }),
  NT5({ id:'q_l5_7', question:"Surat Paulus yang paling pendek ialah?", options:["Filemon","Galatia","2 Yohanes","Titus"], correctAnswer:0, explanation:"Filemon — 25 ayat. [Filemon 1-25]" }),
  NT5({ id:'q_l5_8', question:"Siapakah penulis Injil yang dipanggil 'teman seperjalanan Paulus'?", options:["Lukas","Markus","Matius","Yohanes"], correctAnswer:0, explanation:"Kisah 16:10 — penggunaan 'kami' menandakan Lukas menyertai Paulus. [Kisah 16:10]" }),
  OT5({ id:'q_l5_9', question:"Kitab yang mencatat 'Pada mulanya Allah menciptakan langit dan bumi'?", options:["Kejadian","Mazmur","Yesaya","Yohanes"], correctAnswer:0, explanation:"Kejadian 1:1. [Kejadian 1:1]" }),
  NT5({ id:'q_l5_10', question:"Injil yang paling pendek ialah?", options:["Markus","Matius","Lukas","Yohanes"], correctAnswer:0, explanation:"Markus — 16 pasal. [Markus 1-16]" }),
  NT5({ id:'q_l5_11', question:"Injil yang paling panjang ialah?", options:["Matius","Lukas","Markus","Yohanes"], correctAnswer:0, explanation:"Matius — 28 pasal. [Matius 1-28]" }),
  NT5({ id:'q_l5_12', question:"Surat Pertama Yohanes dimulai dengan kata-kata yang sama seperti?", options:["Injil Yohanes","Matius","Wahyu","Galatia"], correctAnswer:0, explanation:"1 Yohanes 1:1 — 'Apa yang telah ada sejak semula' — sama dengan Yohanes 1:1. [1 Yohanes 1:1, Yohanes 1:1]" }),
  OT5({ id:'q_l5_13', question:"'Dalam mulanya adalah Firman' merupakan frasa dari kitab?", options:["Yohanes 1","Kejadian 1","Wahyu 1","Efesus 1"], correctAnswer:0, explanation:"Yohanes 1:1 — 'Dalam mulanya adalah Firman, Firman itu bersama-sama dengan Allah'. [Yohanes 1:1]" }),
  OT5({ id:'q_l5_14', question:"Yesus membaca kitab dari Nabi Yesaya di kota?", options:["Nazaret","Yerusalem","Kapernaum","Betlehem"], correctAnswer:0, explanation:"Lukas 4:16-19 — Yesus membaca Yesaya 61 di Nazaret. [Lukas 4:16-19]" }),
  NT5({ id:'q_l5_15', question:"'Surat-surat am' (General Epistles) terdiri dari berapa kitab?", options:["7 kitab","5 kitab","10 kitab","3 kitab"], correctAnswer:0, explanation:"Yakobus, 1-2 Petrus, 1-2-3 Yohanes, Yudas. [Surat-surat Am]" }),
  OT5({ id:'q_l5_16', question:"Kitab Pengkhotbah dalam bahasa Ibrani dikenali sebagai?", options:["Qohelet","Torah","Nevi'im","Khetuvim"], correctAnswer:0, explanation:"Qohelet = orang yang mengumpulkan orang ramai atau pemikir. [Pengkhotbah 1:1]" }),
  OT5({ id:'q_l5_17', question:"'Taurat' (Torah) terdiri dari berapa kitab?", options:["5 kitab","7 kitab","10 kitab","12 kitab"], correctAnswer:0, explanation:"Taurat = Kejadian, Keluaran, Imamat, Bilangan, Ulangan. [Kejadian - Ulangan]" }),
  OT5({ id:'q_l5_18', question:"Kitab yang menutup sejarah Perjanjian Lama ialah?", options:["Maleakhi","Daniel","Ezra","2 Tawarikh"], correctAnswer:0, explanation:"Maleakhi menutup sejarah PL. [Maleakhi 1-3]" }),
  NT5({ id:'q_l5_19', question:"Kitab Pertama Korintus ditulis kepada jemaah di kota?", options:["Korintus","Roma","Efesus","Tesalonika"], correctAnswer:0, explanation:"1 Korintus 1:1-2 — Paulus menulis kepada jemaat di Korintus. [1 Korintus 1:1-2]" }),
  NT5({ id:'q_l5_20', question:"Kitab Ibrani ditujukan kepada orang?", options:["Yahudi","Samaria","Rum","Yunani"], correctAnswer:0, explanation:"Ibrani 1:1 — 'Baru-baru ini Allah telah berbicara kepada kita melalui Anak'. Umat Yahudi Kristen. [Ibrani 1:1]" }),
  // Hebrew-Greek terminology (15)
  OT5({ id:'q_l5_21', question:"'Yesus' dalam bahasa Ibrani bermaksud?", options:["YHWH menyelamatkan","Allah besertaku","Anak Domba","Mesias"], correctAnswer:0, explanation:"Matius 1:21 — 'Yesus' = 'Yosua' = 'YHWH menyelamatkan'. [Matius 1:21]" }),
  OT5({ id:'q_l5_22', question:"'Imanuel' dalam bahasa Ibrani bermaksud?", options:["Allah menyertai kita","Tuhan raja","Bapa kekal","Anak manusia"], correctAnswer:0, explanation:"Yesaya 7:14 — 'Imanuel' = 'Immanu El' = 'Allah dengan kita'. [Yesaya 7:14]" }),
  OT5({ id:'q_l5_23', question:"'Kristus' dalam bahasa Yunani bermaksud sama dengan Ibrani?", options:["Messiah","YHWH","Rabbi","Yesus"], correctAnswer:0, explanation:"Kristus (Greek) = Messiah (Ibrani) = 'yang diurapi'. [Yohanes 1:41]" }),
  OT5({ id:'q_l5_24', question:"'Abba' dalam bahasa Aram bermaksud?", options:["Bapa","Tuhan","Anak","Mujizat"], correctAnswer:0, explanation:"Markus 14:36 — 'Abba, ya Bapa'. Bapa dalam doa di Getsemani. [Markus 14:36]" }),
  OT5({ id:'q_l5_25', question:"'Hosanna' berasal dari bahasa Ibrani yang bermaksud?", options:["Selamatkanlah kami","Terpujilah Tuhan","Datanglah","Bersukacitalah"], correctAnswer:0, explanation:"Matius 21:9 — 'Hosana bagi Anak Daud', dari Ibrani 'yasha' = menyelamatkan. [Matius 21:9]" }),
  OT5({ id:'q_l5_26', question:"'Marana tha' (1 Korintus 16:22) bermaksud?", options:["Tuhan kami datanglah","Selamatkanlah kami","Bersukacita","Aku percaya"], correctAnswer:0, explanation:"1 Korintus 16:22 — 'Marana tha' = 'Marana' atau 'Maran atha' = Tuhan kami datanglah. [1 Korintus 16:22]" }),
  OT5({ id:'q_l5_27', question:"'Torah' dalam bahasa Ibrani bermaksud?", options:["Hukum/Pengajaran","Nabi","Mazmur","Kebijaksanaan"], correctAnswer:0, explanation:"'Torah' = 'Hukum/Pengajaran'. Sinonim dengan Pentateuch. [Mazmur 1:2]" }),
  OT5({ id:'q_l5_28', question:"'Paracletos' (Yohanes 14) dalam bahasa Yunani bermaksud?", options:["Penolong","Penghibur","Pelindung","Penolong rohani"], correctAnswer:0, explanation:"Yohanes 14:26 — 'Paracletos' = 'yang dipanggil untuk membantu'. [Yohanes 14:26]" }),
  OT5({ id:'q_l5_29', question:"Kata Ibrani 'YHWH' tertera di?", options:["Loh batu 10 Perintah","Tabut Perjanjian","Mazmur","Hanya disuarakan"], correctAnswer:0, explanation:"Keluaran 20:1-17 — YHWH diukir pada loh batu. [Keluaran 20]" }),
  OT5({ id:'q_l5_30', question:"Yesus 'Akulah' (Yunani: ego eimi) terdapat berapa kali dalam Injil Yohanes?", options:["7 kali","5 kali","9 kali","3 kali"], correctAnswer:0, explanation:"Tujuh 'ego eimi' mutlak dalam Yohanes: 6:35, 8:24, 8:28, 8:58, 13:19, 18:5, 18:8. [Yohanes 6:35, 8:24, 8:28, 8:58, 13:19, 18:5, 18:8]" }),
  OT5({ id:'q_l5_31', question:"'Gehenna' dalam Perjanjian Baru merujuk kepada?", options:["Neraka (lembah Hinnom)","Taman Firdaus","Tempat orang mati","Hades"], correctAnswer:0, explanation:"Matius 5:22 — 'Gehenna' dari Lembah Hinnom di luar Yerusalem. [Matius 5:22]" }),
  OT5({ id:'q_l5_32', question:"'Sheol' (Ibrani) atau 'Hades' (Yunani) merujuk kepada?", options:["Tempat orang mati","Neraka","Surga","Taman Eden"], correctAnswer:0, explanation:"Kejadian 37:35 — 'Aku akan turun ke dalam dunia orang mati (Sheol) kepada anakku'. [Kejadian 37:35]" }),
  OT5({ id:'q_l5_33', question:"Kata 'Bait Allah' (Ibrani: Hekal) merujuk kepada?", options:["Rumah ibadat besar","Rumah sendiri","Kuil dewa","Istana raja"], correctAnswer:0, explanation:"2 Raja-raja 18:15 — 'Hekal' merujuk rumah besar. Bait Allah di Yerusalem. [2 Raja-raja 18:15]" }),
  OT5({ id:'q_l5_34', question:"'Berit' (Ibrani) bermaksud?", options:["Perjanjian","Pentakosta","Kasih","Berkat"], correctAnswer:0, explanation:"'Berit' = 'Perjanjian' — Tanah Perjanjian, Berit Lama, Berit Baharu. [Kejadian 9:9]" }),
  OT5({ id:'q_l5_35', question:"'Koinonia' (Yunani) bermaksud?", options:["Persekutuan","Kasih","Berkat","Kepujian"], correctAnswer:0, explanation:"Kisah 2:42 — 'Koinonia' = persekutuan, persekutuan orang percaya. [Kisah 2:42]" }),
  // Number symbolism (10)
  OT5({ id:'q_l5_36', question:"40 hari lamanya hujan di zaman Nuh berbanding 40 tahun umat Israel di padang belantara melambangkan?", options:["Tempoh ujian","Zaman damai","Kehidupan biasa","Era raja"], correctAnswer:0, explanation:"Bilangan 40 dalam Kitab Suci melambangkan tempoh ujian/penantian. [Kejadian 7:12, Bilangan 14:33]" }),
  OT5({ id:'q_l5_37', question:"Berapa jumlah bangsa Israel (suku)?", options:["10","12","7","14"], correctAnswer:1, explanation:"Kejadian 49:28 — 'Dua belas suku Israel'. [Kejadian 49:28]" }),
  OT5({ id:'q_l5_38', question:"Bilangan kesempurnaan dalam Kitab Suci ialah?", options:["3","7","12","40"], correctAnswer:1, explanation:"Tujuh dalam Kitab Suci melambangkan kesempurnaan: 7 hari penciptaan, 7 tahun penternakan, dll. [Kejadian 1-2]" }),
  OT5({ id:'q_l5_39', question:"Tiga hari dalam Kitab Suci (contoh Yunus 3 hari dalam ikan) merupakan gambaran tentang?", options:["Hari kebangkitan Kristus","Waktu biasa","Tanda","Larangan"], correctAnswer:0, explanation:"Yunus 2:1, Matius 12:40 — 'Tiga hari dan tiga malam' meramalkan kebangkitan Kristus. [Yunus 2:1, Matius 12:40]" }),
  OT5({ id:'q_l5_40', question:"Dua belas rasul ialah siapa?", options:["Yesus + 12 rasul","12 nabi","12 imam","12 patriot"], correctAnswer:0, explanation:"Matius 10:2-4 — daftar dua belas rasul: Simon Petrus, Andreas, Yakobus, Yohanes, Filipus, Bartolomeus, Matius, Tomas, Yakobus anak Alfeus, Tadius, Simon, Yudas Iskariot. [Matius 10:2-4]" }),
  OT5({ id:'q_l5_41', question:"Yesus memilih 70 murid tambahan sebagai tanda?", options:["Tujuh kali lipat kepada 12 (pelengkap sempurna)","Pengorbanan","Kebetulan","Tanda rohani"], correctAnswer:0, explanation:"Lukas 10:1 — 70 pengutus. 70 = 10x7 (kesempurnaan). [Lukas 10:1]" }),
  OT5({ id:'q_l5_42', question:"Yesus mengatakan 'tiada seorangpun yang mengangkat rumah dari batu-bata yang lebih baik dari pada Bait Suci'? Di mana?", options:["Markus 14:58","Yohanes 2:19","Matius 26:61","Lukas 21:5"], correctAnswer:1, explanation:"Yohanes 2:19 — 'Rombeng Bait Allah ini, dan dalam tiga hari Aku akan mendirikannya kembali'. [Yohanes 2:19]" }),
  OT5({ id:'q_l5_43', question:"Yesus berkata 'akan ada tanda-tanda di matahari, bulan dan bintang-bintang' di?", options:["Lukas 21:25","Matius 24:29","Wahyu 6:12","Markus 13:24"], correctAnswer:0, explanation:"Lukas 21:25 — 'Akan ada tanda-tanda pada matahari, bulan dan bintang-bintang'. [Lukas 21:25]" }),
  OT5({ id:'q_l5_44', question:"Tiga berkat Abraham dalam Kejadian 12:1-3 menyebut?", options:["Tanah, keturunan, berkat","Materi, kuasa, nama","Harta, anak, kebijaksanaan","Hak milik, harta, perdamaian"], correctAnswer:0, explanation:"Kejadian 12:1-3 — 'Aku akan menjadikanmu bangsa yang besar, dan memberkati engkau'. Tiga komponen: keturunan, tanah, berkat universal. [Kejadian 12:1-3]" }),
  OT5({ id:'q_l5_45', question:"'Seratus empat puluh empat ribu' dalam Wahyu 7 membawa makna?", options:["12x12x1000 = kelengkapan umat Allah","Hanya literal","Nombor malaikat","Jumlah malaikat"], correctAnswer:0, explanation:"Wahyu 7:4-8 — 144,000 = 12 (suku) x 12 (rasul) x 1000 (melambangkan kelengkapan). [Wahyu 7:4-8]" }),
  // 'Who said this?' (15)
  OT5({ id:'q_l5_46', question:"'Tuhanlah yang memberi, Tuhanlah yang mengambil, terpujilah nama Tuhan' — siapakah?", options:["Ayub","Musa","Daud","Yesus"], correctAnswer:0, explanation:"Ayub 1:21. [Ayub 1:21]" }),
  OT5({ id:'q_l5_47', question:"'Aku ini sangat susah hati, sampai pada saat aku mati' — kata-kata siapa?", options:["Elia","Musa","Daud","Yesus"], correctAnswer:0, explanation:"1 Raja-raja 19:4 — Elia di bawah pohon mudar, meminta mati. [1 Raja-raja 19:4]" }),
  OT5({ id:'q_l5_48', question:"'Tuhan, berapa lama lagi aku harus bertahan? — kata Daniel", options:["Daniel 12:6","Daniel 7:21","Daniel 9:2","Daniel 6:5"], correctAnswer:0, explanation:"Daniel 12:6 — 'Berapa lama lagi sampai akhir perkara-perkara yang ajaib ini'. [Daniel 12:6]" }),
  NT5({ id:'q_l5_49', question:"'Di sini aku berdiri, di bawah次序 takhta kasih karunia' — kata?", options:["Ratu Ester","Musa","Maria","Yusuf"], correctAnswer:0, explanation:"Ester 5:1-2 — Ester mendekati takhta raja. [Ester 5:1-2]" }),
  OT5({ id:'q_l5_50', question:"'Tuhan, masuklah ke dalam rumahku, sebab aku tidak layak' — kata?", options:["Petrus","Yusuf","David","Abraham"], correctAnswer:0, explanation:"Lukas 5:8 — Petrus setelah tangkapan ikan. [Lukas 5:8]" }),
  NT5({ id:'q_l5_51', question:"'Aku tidak tahu apa yang kamu bicarakan' — kata?", options:["Petrus menyangkal Yesus","Yudas","Annas","Kayafas"], correctAnswer:0, explanation:"Matius 26:70 — Petrus menyangkal Yesus. [Matius 26:70]" }),
  NT5({ id:'q_l5_52', question:"'Tuhan, jika Engkau berkenan, biarlah cawan ini lalu dari padaku' — kata?", options:["Yesus di Getsemani","Petrus","Yudas","Yakobus"], correctAnswer:0, explanation:"Lukas 22:42 — doa di Taman Getsemani. [Lukas 22:42]" }),
  NT5({ id:'q_l5_53', question:"'Ya Abba, ya Bapa, segala sesuatu mungkin bagi-Mu' — kata?", options:["Yesus","Petrus","Paulus","Yohanes"], correctAnswer:0, explanation:"Markus 14:36. [Markus 14:36]" }),
  NT5({ id:'q_l5_54', question:"'Mengapa Engkau singgah di rumah orang berdosa?' — kata?", options:["Orang Farisi tentang Zakheus","Yudas tentang Maria","Yohanes tentang Yesus","Annas tentang Petrus"], correctAnswer:0, explanation:"Lukas 19:7 — 'Ia singgah untuk menjadi tamu orang berdosa'. [Lukas 19:7]" }),
  OT5({ id:'q_l5_55', question:"'Bukankah aku menjaga domba-domba ayahku?' — kata?", options:["Musa","Daud","Saul","Yusuf"], correctAnswer:0, explanation:"1 Samuel 17:34-37 — Daud tentang penjagaan domba. [1 Samuel 17:34-37]" }),
  OT5({ id:'q_l5_56', question:"'Siapakah aku ini sehingga akan memberkati aku?' — kata?", options:["Abraham","Musa","Daud","Yesus"], correctAnswer:0, explanation:"Kejadian 18:7-9 — Abraham kepada TUHAN. [Kejadian 18:7-9]" }),
  OT5({ id:'q_l5_57', question:"'Jangan takut, sebab Aku menyertai engkau' — kata TUHAN kepada?", options:["Yusuf (di Mesir)","Abraham","Musa","Daud"], correctAnswer:0, explanation:"Kejadian 26:24 — 'Jangan takut, sebab Aku menyertai engkau'. [Kejadian 26:24]" }),
  NT5({ id:'q_l5_58', question:"'Tuhan, beri tahu kami, jikalau kepada-Mu kami harus memberikan cukup wang' — kata?", options:["Petrus (tidak ada dalam Alkitab; ini ilusi)","Tomas","Yudas","Yohanes"], correctAnswer:3, explanation:"Yohanes 6:5-7 — Filipus di Kafarnaum, tetapi dialog Yohanes. [Yohanes 6:5-7] (NOT masuk dalam Alkitab kecuali diri varians lain)" }),
  OT5({ id:'q_l5_59', question:"'Pintu gerbang kehidupan ialah milik TUHAN' — kata Mazmur?", options:["Mazmur 118","Mazmur 23","Mazmur 119","Mazmur 1"], correctAnswer:0, explanation:"Mazmur 118:20 — 'Inilah pintu TUHAN, tempat orang benar masuk'. [Mazmur 118:20]" }),
  OT5({ id:'q_l5_60', question:"'Sebab pengalaman pahit menghasilkan ketekunan, dan ketekunan menghasilkan...'?", options:["Karakter, dan karakter menghasilkan pengharapan","Kebahagiaan","Kesedihan","Kesengsaraan"], correctAnswer:0, explanation:"Roma 5:3-4 — 'pengalaman pahit menghasilkan ketekunan, ketekunan menghasilkan karakter'. [Roma 5:3-4]" }),
  // Cross-testament typology (15)
  OT5({ id:'q_l5_61', question:"Kurban domba Paskah (Pesach) di PL merupakan kiasan kepada?", options:["Kurban Kristus di kayu salib","Upacara biasa","Upacara raja","Perjamuan orang Yahudi"], correctAnswer:0, explanation:"1 Korintus 5:7 — 'Kristus, Anak Domba Paskah kita, telah disembelih'. [1 Korintus 5:7, Keluaran 12]" }),
  OT5({ id:'q_l5_62', question:"Ular tembaga yang ditinggikan Musa (Bilangan 21) merupakan gambaran tentang?", options:["Penyaliban Kristus","Tongkat kerajaan","Bintang","Hujan"], correctAnswer:0, explanation:"Yohanes 3:14 — 'Seperti Musa meninggikan ular di padang gurun, demikianlah Anak Manusia harus ditinggikan'. [Yohanes 3:14]" }),
  OT5({ id:'q_l5_63', question:"Bait Suci Salomo menggambarkan?", options:["Tubuh Kristus","Istana raja","Surga","Bangsa Israel"], correctAnswer:0, explanation:"Yohanes 2:19-21 — 'Ia berkata tentang Bait Suci tubuh-Nya'. [Yohanes 2:19-21]" }),
  OT5({ id:'q_l5_64', question:"'Manna' (roti dari surga) di padang gurun merupakan gambaran tentang?", options:["Roti Hidup (Yesus)","Biasa","Anugerah","Hukuman"], correctAnswer:0, explanation:"Yohanes 6:49-51 — 'Bapakmu makan manna di padang gurun dan mati. Roti yang turun dari surga'. [Yohanes 6:49-51]" }),
  OT5({ id:'q_l5_65', question:"Batu yang dipancarkan Daud dari mata air mengatasi Goliat ialah gambaran tentang?", options:["Kemenangan Kristus atas Iblis","Biasa","Kemenangan tentara","Kemenangan raja"], correctAnswer:0, explanation:"1 Samuel 17:49 — Daud melawan Goliat dengan satu batu = Kristus mengalahkan kematian. [1 Samuel 17:49]" }),
  OT5({ id:'q_l5_66', question:"Yusuf yang dijual ke Mesir (Kejadian 37) merupakan gambaran tentang?", options:["Kristus yang dijual oleh Yudas","Raja","Hamba biasa","Hakim"], correctAnswer:0, explanation:"Matius 26:15 — Yudas menjual Yesus 30 keping perak seperti Yusuf dijual saudara-saudaranya. [Matius 26:15, Kejadian 37:28]" }),
  OT5({ id:'q_l5_67', question:"Pengorbanan Ishak di gunung Moria (Kejadian 22) merupakan gambaran tentang?", options:["Pengorbanan Kristus di Golgota","Percobaan biasa","Pertempuran","Pengorbanan biasa"], correctAnswer:0, explanation:"Kejadian 22:1-14 — Ishak yang hampir dikorbankan seperti Kristus. [Kejadian 22:1-14, Yohanes 3:16]" }),
  OT5({ id:'q_l5_68', question:"Yesus memakai 'Adam kedua' (1 Korintus 15:45) bermaksud?", options:["Adam ialah manusia pertama, Kristus yang bangkit menjadi manusia kedua","Dosa Adam","Kesengsaraan","Anak sulung"], correctAnswer:0, explanation:"1 Korintus 15:45 — 'Adam yang terakhir menjadi roh yang memberi hidup'. [1 Korintus 15:45]" }),
  OT5({ id:'q_l5_69', question:"Anak Daud berkenaan dengan?", options:["Keturunan Daud → Mesias → Yesus","Anak zaman dulu","Anak raja","Anak biasa"], correctAnswer:0, explanation:"Yesus 'Anak Daud' (Matius 1:1; Markus 10:47) — keturunan Mesias dari Daud. [Matius 1:1]" }),
  OT5({ id:'q_l5_70', question:"'Anak Manusia' (Ibrani: Ben Adam) adalah?", options:["Istilah Kristus untuk diri-Nya dari Daniel 7","Anak Adam","Anak orang","Sebutan rohani"], correctAnswer:0, explanation:"Daniel 7:13 — 'Aku terus melihat sampai takhta diletakkan, datanglah seorang seperti Anak Manusia'. [Daniel 7:13]" }),
  OT5({ id:'q_l5_71', question:"Yesus adalah 'Anak Domba Allah' yang menggayakan diri-Nya kepada?", options:["Kurban domba Paskah","Domba biasa","Hewan","Kesucian"], correctAnswer:0, explanation:"Yohanes 1:29 — 'Anak Domba Allah'. Dikorbankan untuk keselamatan. [Yohanes 1:29]" }),
  OT5({ id:'q_l5_72', question:"Keturunan perempuan (Kejadian 3:15) menggenapi pada?", options:["Maria bayi Yesus","Ester","Yusuf","Salomo"], correctAnswer:0, explanation:"Kejadian 3:15 — 'Keturunan perempuan itu akan meremukkan kepalamu'. [Kejadian 3:15]" }),
  OT5({ id:'q_l5_73', question:"'Muzizat di laut merah' merupakan kiasan kepada?", options:["Pembebasan oleh Kristus dari dosa","Pembasmian musuh biasa","Perjalanan biasa","Pertempuran biasa"], correctAnswer:0, explanation:"Keluaran 14 — pembebasan Israel dari Mesir merupakan gambaran pembebasan oleh Kristus. [Keluaran 14]" }),
  OT5({ id:'q_l5_74', question:"'Pohon kehidupan' di Taman Eden kembali di?", options:["Yerusalem Baru","Tempat lainnya","Surga","Taman"], correctAnswer:0, explanation:"Wahyu 22:2 — 'Di antara jalan kota itu dan di tepi sungai, di sini dan di sana, ada pohon kehidupan'. [Wahyu 22:2]" }),
  OT5({ id:'q_l5_75', question:"'Air yang mengalir dari Bait Suci' (Yehezkiel 47) merupakan gambaran tentang?", options:["Roh Kudus dan karunia-karuniaNya","Air biasa","Hujan biasa","Sungai"], correctAnswer:0, explanation:"Yehezkiel 47:1-12 — sungai yang mengalir dari Bait Suci menyembuhkan air. [Yehezkiel 47:1-12]" }),
  // Cultic/liturgical specifics (15)
  OT5({ id:'q_l5_76', question:"Hari raya Yahudi yang terbesar ialah?", options:["Paskah (Pesach)","Pentakosta","Pondok Daun","Purim"], correctAnswer:0, explanation:"Keluaran 12 — Paskah institusi untuk peringatan. [Keluaran 12]" }),
  OT5({ id:'q_l5_77', question:"Imam Besar Yahudi hanya boleh masuk ke Tempat Mahakudus berapa kali setahun?", options:["Sekali setahun","Tiga kali","Setiap hari","Tujuh kali"], correctAnswer:0, explanation:"Ibrani 9:7 — Imam Besar masuk sekali setahun dengan darah korban. [Ibrani 9:7]" }),
  OT5({ id:'q_l5_78', question:"Pada hari apakah Perjamuan Terakhir Yesus dengan murid?", options:["Hari pertama Paskah","Hari kedua Paskah","Paskah","Pondok Daun"], correctAnswer:0, explanation:"Matius 26:17 — 'Pada hari pertama perayaan Paskah'. [Matius 26:17]" }),
  OT5({ id:'q_l5_79', question:"Berapa lama lamanya Hari Raya Pondok Daun (Sukot)?", options:["7 hari","3 hari","5 hari","10 hari"], correctAnswer:0, explanation:"Imamat 23:34 — 'Pada hari kelima belas bulan ketujuh... selama tujuh hari'. [Imamat 23:34]" }),
  OT5({ id:'q_l5_80', question:"Tabut Perjanjian di Bait Suci mengandungi?", options:["Loh batu 10 Perintah","Manna","Tongkat Harun","Ketiganya"], correctAnswer:3, explanation:"Ibrani 9:4 — Tabut berisi loh batu, bejana manna emas, tongkat Harun. [Ibrani 9:4]" }),
  OT5({ id:'q_l5_81', question:"Roti sajian (Showbread) di Kemah Suci ada berapa?", options:["12 roti","7 roti","5 roti","10 roti"], correctAnswer:0, explanation:"Imamat 24:5 — 'Engkau harus mengambil tepung halus dan membakar dua belas roti'. [Imamat 24:5]" }),
  OT5({ id:'q_l5_82', question:"Hukuman terhadap anak-anak Harun (Nadab dan Abihu) yang mempersembahkan 'api asing' ialah?", options:["Api membunuh mereka","Batu","Diasingkan","Baik-baik"], correctAnswer:0, explanation:"Imamat 10:1-2 — 'Muncullah api dari hadapan TUHAN dan memakan mereka'. [Imamat 10:1-2]" }),
  OT5({ id:'q_l5_83', question:"Hukuman kepada orang yang bekerja pada hari Sabat?", options:["Kena hukuman mati","Sebab biasa","Sebab biasa","Diam-diam"], correctAnswer:0, explanation:"Keluaran 31:14-15 — 'Siapa yang melanggar hari Sabat harus mati'. [Keluaran 31:14-15]" }),
  OT5({ id:'q_l5_84', question:"Mesias datang dari suku?", options:["Yehuda","Lewi","Benyamin","Efraim"], correctAnswer:0, explanation:"Kejadian 49:10 — 'Tongkat kekuasaan tidak akan beranjak dari Yehuda'. [Kejadian 49:10]" }),
  OT5({ id:'q_l5_85', question:"Setan menggoda Yesus berapa lama di padang gurun?", options:["40 hari","30 hari","3 hari","7 hari"], correctAnswer:0, explanation:"Matius 4:1-2 — 'Yesus berpuasa empat puluh hari empat puluh malam'. [Matius 4:1-2]" }),
  OT5({ id:'q_l5_86', question:"Kenaikan Yesus ke surga berlaku di?", options:["Bukit Zaitun","Bukit Sinai","Yerusalem","Bukit Moria"], correctAnswer:0, explanation:"Kisah 1:9-12 — 'Ia terangkat di hadapan mereka, dan awan menyembunyikan-Nya dari penglihatan mereka'. [Kisah 1:9-12]" }),
  OT5({ id:'q_l5_87', question:"Tongkat Harun yang bersemi merupakan tanda?", options:["Pilihan Allah atas suku Lewi","Penguasaan raja","Kesembuhan","Anak-anak"], correctAnswer:0, explanation:"Bilangan 17:1-8 — tongkat Harun dari keluarga Lewi bertunas sebagai bukti pilihan Allah. [Bilangan 17:1-8]" }),
  OT5({ id:'q_l5_88', question:"Yesus dibandingkan dengan Nabi Musa dalam kitab Ibrani?", options:["Ibrani 3:1-6","Matius 5","Wahyu 1","Lukas 10"], correctAnswer:0, explanation:"Ibrani 3:1-6 — Yesus dianggap lebih besar dari Musa. [Ibrani 3:1-6]" }),
  OT5({ id:'q_l5_89', question:"Sacrifices animals di PL melambangkan korban Kristus. Tujuan asalnya untuk?", options:["Menutupi dosa","Menyembah berhala","Mencari hiburan","Menikmati rasa"], correctAnswer:0, explanation:"Ibrani 10:4 — 'Tidak mungkin darah lembu jantan dan darah kambing menghapus dosa'. [Ibrani 10:4]" }),
  OT5({ id:'q_l5_90', question:"Ketiga-tiga anak Abraham ialah?", options:["Ismail, Ishak, anak-anak Ketura","Ishak, Yakub, Yusuf","Ishak, Ismail, Esau","Ishak, Yakub, Benyamin"], correctAnswer:0, explanation:"Kejadian 25:1-2 — Abraham mengambil Ketura sebagai isteri (selepas Sara), yang melahirkan anak-anak. [Kejadian 25:1-2]" }),
  // Eschatology (10)
  NT5({ id:'q_l5_91', question:"Tanda-tanda akhir zaman yang disebut Yesus termasuk peperangan, gempa bumi, kelaparan, penyakit, dan?", options:["Tanda-tanda di langit","Sajak","Badai biasa","Gerhana"], correctAnswer:0, explanation:"Matius 24:6-8 — 'Kamu akan mendengar tentang peperangan'. Tanda-tanda di matahari, bulan, dan bintang-bintang. [Matius 24:6-8]" }),
  NT5({ id:'q_l5_92', question:"Kitab Wahyu menyebut 'Yerusalem Baru' turun dari?", options:["Surga","Tanah","Laut","Tempat biasa"], correctAnswer:0, explanation:"Wahyu 21:2 — 'Aku melihat kota yang kudus, Yerusalem baru, turun dari surga'. [Wahyu 21:2]" }),
  NT5({ id:'q_l5_93', question:"'Yang pertama keluar ialah kerajaan 1000 tahun' merujuk kepada?", options:["Millenium (Kerajaan 1000 tahun)","Hari pertama","Kerajaan biasa","Kerajaan fana"], correctAnswer:0, explanation:"Wahyu 20:1-6 — 'Millenium' = 1000 tahun Kerajaan Kristus. [Wahyu 20:1-6]" }),
  NT5({ id:'q_l5_94', question:"'Binatang Pertama' (Wahyu 13:1-10) datang dari mana?", options:["Laut","Tanah","Laut dalam","Pohon"], correctAnswer:0, explanation:"Wahyu 13:1 — 'Seekor binatang keluar dari laut, ia memiliki tujuh kepala dan sepuluh tanduk'. [Wahyu 13:1-10]" }),
  NT5({ id:'q_l5_95', question:"'Naga Besar' (Wahyu 12) dikenali sebagai?", options:["Iblis / Setan","Binatang","Malaikat","Nabi"], correctAnswer:0, explanation:"Wahyu 12:9 — 'Naga besar itu adalah iblis, yaitu Iblis dan Setan, yang menyesatkan seluruh dunia'. [Wahyu 12:9]" }),
  NT5({ id:'q_l5_96', question:"Di akhir zaman, Iblis akan dibuang ke?", options:["Laut api dan belerang","Surga","Neraka sementara","Tempat biasa"], correctAnswer:0, explanation:"Wahyu 20:10 — 'Iblis yang menyesatkan mereka dilemparkan ke dalam laut api dan belerang'. [Wahyu 20:10]" }),
  NT5({ id:'q_l5_97', question:"Kitab Wahyu menyebut 'Langit Baru dan Bumi Baru' di mana?", options:["Wahyu 21:1","Wahyu 20:1","Wahyu 22:1","Wahyu 19:1"], correctAnswer:0, explanation:"Wahyu 21:1 — 'Aku melihat langit yang baru dan bumi yang baru'. [Wahyu 21:1]" }),
  NT5({ id:'q_l5_98', question:"Yesus akan datang semula sebagai?", options:["Hakim dan Raja","Hamba","Pekerja","Biasa"], correctAnswer:0, explanation:"Matius 25:31-46 — 'Apabila Anak Manusia datang dalam kemuliaan-Nya'. [Matius 25:31-46]" }),
  NT5({ id:'q_l5_99', question:"Penghakiman terakhir di Wahyu 20 ialah?", options:["Penghakiman Hakim Putih Besar","Penghakiman Bait Suci","Penghakiman Rumah","Penghakiman biasa"], correctAnswer:0, explanation:"Wahyu 20:11-15 — Hakim Putih Besar. [Wahyu 20:11-15]" }),
  NT5({ id:'q_l5_100', question:"Pada akhir, 'semuanya dijadikan baru' terdapat dalam?", options:["Wahyu 21:5","Wahyu 22:5","Wahyu 20:5","Wahyu 19:5"], correctAnswer:0, explanation:"Wahyu 21:5 — 'Lihatlah, Aku menjadikan semuanya baru'. [Wahyu 21:5]" }),
];

console.log(`Level 5 entries ready: ${LEVEL5.length}`);

// ============================================================
// LEVEL TEKA-GAMBAR (28 Bible character/place/item replacements)
//   teka_21-28: saints (8) → Bible characters
//   teka_29-33: popes (5) → Bible prophets/kings
//   teka_34-40: liturgical (7) → Bible items/places
//   teka_41-43: liturgical (3) → Bible items/places
//   teka_44-48: churches (5) → Bible holy places
// ============================================================
const TEKA = [
  // 21-28: Bible characters (was saints)
  { id:'teka_21', question:"Siapakah tokoh ini?", options:["Musa","Elia","Elisya","Yunus"], correctAnswer:0, explanation:"Musa — memimpin bangsa Israel keluar dari Mesir. [Keluaran 3-14]", category:'old_testament', level:2, difficulty:'easy', gameMode:'teka-gambar' },
  { id:'teka_22', question:"Siapakah ini?", options:["Adam","Abraham","Daud","Salomo"], correctAnswer:0, explanation:"Adam — manusia pertama yang diciptakan Allah. [Kejadian 2-3]", category:'old_testament', level:2, difficulty:'easy', gameMode:'teka-gambar' },
  { id:'teka_23', question:"Siapakah nabi ini?", options:["Nuh","Ibrahim","Ismail","Ishak"], correctAnswer:0, explanation:"Nuh — membina bahtera untuk menyelamatkan keluarganya dari banjir besar. [Kejadian 6-9]", category:'old_testament', level:2, difficulty:'easy', gameMode:'teka-gambar' },
  { id:'teka_24', question:"Siapakah ini?", options:["Musa","Aaron","Harun","Yusuf"], correctAnswer:0, explanation:"Musa — pemimpin bangsa Israel dan penerima 10 Perintah. [Keluaran 3-20]", category:'old_testament', level:2, difficulty:'easy', gameMode:'teka-gambar' },
  { id:'teka_25', question:"Siapakah tokoh ini?", options:["Daud","Salomon","Saul","Yusuf"], correctAnswer:0, explanation:"Daud — raja Israel kedua, mengalahkan Goliat, pengarang Mazmur. [1 Samuel 16-17, 2 Samuel 1-24]", category:'old_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_26', question:"Siapakah ini?", options:["Salomon","Daud","Ezakia","Hiskia"], correctAnswer:0, explanation:"Salomo — anak Daud, raja bijak yang membangun Bait Suci Pertama. [1 Raja-raja 1-11]", category:'old_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_27', question:"Siapakah nabi ini?", options:["Elia","Elisya","Yesaya","Yermia"], correctAnswer:0, explanation:"Elia — napi yang mengalahkan nabi-nabi Baal di Gunung Karmel. [1 Raja-raja 17-19, 2 Raja-raja 1-2]", category:'old_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_28', question:"Siapakah ini?", options:["Yunus","Elia","Nabi Yoel","Nabi Amos"], correctAnswer:0, explanation:"Yunus — nabi yang ditelan ikan besar selama tiga hari. [Yunus 1-4]", category:'old_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  // 29-33: Bible prophets/kings (was popes)
  { id:'teka_29', question:"Siapakah raja ini?", options:["Daud","Saul","Salomo","Yerobeam"], correctAnswer:0, explanation:"Daud — raja Israel kedua, bersahabat dengan Nabi Natan, raja yang beriman. [1 Samuel 16, 2 Samuel 7]", category:'old_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_30', question:"Siapakah nabi ini?", options:["Yesaya","Yeremia","Yehezkiel","Daniel"], correctAnswer:0, explanation:"Yesaya — nabi zaman raja Ahas, menubuatkan tentang Imanuel dan Hamba yang Menderita. [Yesaya 1-66]", category:'old_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_31', question:"Siapakah nabi ini?", options:["Yeremia","Yesaya","Ezekiel","Hosea"], correctAnswer:0, explanation:"Yeremia — nabi yang dipanggil pada usia muda, sering menangis untuk Israel. [Yeremia 1-52]", category:'old_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_32', question:"Siapakah nabi ini?", options:["Daniel","Yehezkiel","Hosea","Yoel"], correctAnswer:0, explanation:"Daniel — nabi di Babel, ditafsirkan mimpi raja, dibuang ke gua singa. [Daniel 1-12]", category:'old_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_33', question:"Siapakah raja ini?", options:["Saul","Daud","Salomo","Yerobeam"], correctAnswer:0, explanation:"Saul — raja pertama Israel, mencarikan keledai lalu diurapi raja. [1 Samuel 9-31]", category:'old_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  // 34-40: Bible items/places (was liturgical)
  { id:'teka_34', question:"Apakah nama objek ini?", options:["Tabut Perjanjian","Mekah","Bejana","Tabernakel"], correctAnswer:0, explanation:"Tabut Perjanjian — kotak yang berisi loh batu 10 Perintah. [Keluaran 25:10-22]", category:'old_testament', level:2, difficulty:'easy', gameMode:'teka-gambar' },
  { id:'teka_35', question:"Apakah nama tempat ini?", options:["Bait Suci","Tabernakel","Sinagog","Bait Salomo"], correctAnswer:0, explanation:"Bait Suci — rumah ibadat orang Yahudi di Yerusalem. [1 Raja-raja 5-8, 2 Tawarikh 2-5]", category:'old_testament', level:2, difficulty:'easy', gameMode:'teka-gambar' },
  { id:'teka_36', question:"Apakah nama objek ini?", options:["Mekah","Tempayan","Bak","Tungku"], correctAnswer:0, explanation:"Mekah — tempayan di mana Yesaya melihat Tuhan dalam penglihatan Bait Suci. [Yesaya 6:1-7]", category:'old_testament', level:2, difficulty:'easy', gameMode:'teka-gambar' },
  { id:'teka_37', question:"Apakah nama tempat ini?", options:["Kemah Suci","Khemah","Rumah","Kuil"], correctAnswer:0, explanation:"Kemah Suci — tempat Musa bertemu Tuhan (Ohel Mo'ed). [Keluaran 33:7-11]", category:'old_testament', level:2, difficulty:'easy', gameMode:'teka-gambar' },
  { id:'teka_38', question:"Apakah nama tempat ini?", options:["Gunung Sinai","Gunung Nebo","Gunung Tabor","Gunung Zaitun"], correctAnswer:0, explanation:"Gunung Sinai — tempat Musa menerima 10 Perintah. [Keluaran 19-20]", category:'old_testament', level:2, difficulty:'easy', gameMode:'teka-gambar' },
  { id:'teka_39', question:"Apakah nama tempat ini?", options:["Yerusalem","Betlehem","Nazaret","Yerikho"], correctAnswer:0, explanation:"Yerusalem — kota Daud dan Bait Suci. [2 Samuel 5, 1 Raja-raja 8]", category:'old_testament', level:2, difficulty:'easy', gameMode:'teka-gambar' },
  { id:'teka_40', question:"Apakah nama tempat ini?", options:["Galilea","Tasik Galilea","Sungai Yordan","Tasik Betesda"], correctAnswer:0, explanation:"Tasik Galilea — tempat Yesus memanggil murid-murid-Nya. [Matius 4:18-22]", category:'new_testament', level:2, difficulty:'easy', gameMode:'teka-gambar' },
  // 41-43: Bible items/places (was liturgical)
  { id:'teka_41', question:"Apakah nama tempat ini?", options:["Bukit Zaitun","Bukit Sinai","Bukit Nebo","Bukit Moria"], correctAnswer:0, explanation:"Bukit Zaitun — tempat Yesus berdoa, kenaikan Yesus ke surga. [Lukas 22:39, Kisah 1:9-12]", category:'new_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_42', question:"Apakah nama tempat ini?", options:["Taman Getsemani","Taman Eden","Taman Nabi","Taman Raja"], correctAnswer:0, explanation:"Taman Getsemani — tempat Yesus berdoa sebelum ditangkap. [Matius 26:36-46]", category:'new_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_43', question:"Apakah nama tempat ini?", options:["Kalvari/Golgota","Taman","Yerusalem","Nazaret"], correctAnswer:0, explanation:"Golgota (Kalvari) — tempat Yesus disalibkan. [Matius 27:33, Yohanes 19:17]", category:'new_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  // 44-48: Bible holy places (was churches)
  { id:'teka_44', question:"Apakah nama tempat ini?", options:["Betlehem","Nazaret","Kapernaum","Yerusalem"], correctAnswer:0, explanation:"Betlehem — kota kelahiran Yesus Kristus. [Matius 2:1, Lukas 2:4-7]", category:'new_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_45', question:"Apakah nama tempat ini?", options:["Nazaret","Yerusalem","Kapernaum","Betlehem"], correctAnswer:0, explanation:"Nazaret — kota tempat Yesus dibesarkan. [Matius 2:23, Lukas 4:16]", category:'new_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_46', question:"Apakah nama tempat ini?", options:["Kapernaum","Nazaret","Betlehem","Yerusalem"], correctAnswer:0, explanation:"Kapernaum — pusat pelayanan Yesus di Galilea. [Matius 4:13, Markus 1:21]", category:'new_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_47', question:"Apakah nama tempat ini?", options:["Yerikho","Yerusalem","Galilea","Sungai Yordan"], correctAnswer:0, explanation:"Yerikho — kota yang ditimbangkan jatuh oleh Yosua. [Yosua 6]", category:'old_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
  { id:'teka_48', question:"Apakah nama tempat ini?", options:["Sungai Yordan","Tasik Galilea","Laut Merah","Sungai Nil"], correctAnswer:0, explanation:"Sungai Yordan — tempat Yohanes membaptis Yesus. [Matius 3:13-17]", category:'new_testament', level:3, difficulty:'medium', gameMode:'teka-gambar' },
];

console.log(`Teka-gambar entries ready: ${TEKA.length}`);

// ============================================================
// APPLY
// ============================================================
const all = JSON.parse(fs.readFileSync(JSON_PATH, 'utf8'));
const byId = new Map();
for (const arr of [LEVEL3, LEVEL4, LEVEL5, TEKA]) for (const r of arr) byId.set(r.id, r);

let replaced = 0, missing = 0;
const updated = all.map((row) => {
  if (byId.has(row.id)) {
    replaced++;
    const n = byId.get(row.id);
    return {
      ...n,
      level: n.level ?? row.level,
      difficulty: n.difficulty ?? row.difficulty,
      category: n.category ?? row.category,
      gameMode: n.gameMode ?? row.gameMode,
    };
  }
  return row;
});

const missingReplacedIds = [...byId.keys()].filter((id) => !updated.some((r) => r.id === id));

console.log(`Replaced: ${replaced}`);
console.log(`Missing IDs (should be 0): ${missingReplacedIds.length}`);
if (missingReplacedIds.length > 0) console.log(`  -> ${missingReplacedIds.slice(0, 5).join(', ')}`);

const remainingNonBible = updated.filter((r) => !['old_testament', 'new_testament'].includes(r.category)).map((r) => r.id);
console.log(`Remaining non-Bible entries: ${remainingNonBible.length}`);
if (remainingNonBible.length > 0 && remainingNonBible.length < 60) console.log(`  -> ${remainingNonBible.slice(0, 60).join(', ')}`);

fs.writeFileSync(JSON_PATH, JSON.stringify(updated, null, 2), 'utf8');
console.log(`Wrote ${JSON_PATH}`);
